## 1. 入力、修正、削除

In [7]:
import pandas as pd

df = pd.DataFrame({
    "名前": ["千尋", "キキ", "ハウル", "ソフィー", "アシタカ"],
    "学年": [1, 2, 1, 3, 2],
    "点数": [85, 92, 78, 95, 88],
    "出席": [90, 95, 80, 98, 85]
})

df

     名前  学年  点数  出席
0    千尋   1  85  90
1    キキ   2  92  95
2   ハウル   1  78  80
3  ソフィー   3  95  98
4  アシタカ   2  88  85

#### # 入力

#### 新しい列の追加

`新しい列変数 = Series`：データセットの要素数と`Series`の要素数が同じでなければならない。異なる場合は`error`

`新しい列変数 = list`：`list`を`Series`に自動的に型変換した後、代入される

`新しい列変数 = scalar値`：データセットの要素数と同じ`Series`（同じ値を持つ）に変換した後、代入される

In [9]:
df["成績"] = ["B", "A", "C", "A+", "B+"]

df

     名前  学年  点数  出席  成績
0    千尋   1  85  90   B
1    キキ   2  92  95   A
2   ハウル   1  78  80   C
3  ソフィー   3  95  98  A+
4  アシタカ   2  88  85  B+

In [10]:
df["生年"] = 2000  # 1つの値 → 同じ値を持つSeriesに変換した後、代入

df

     名前  学年  点数  出席  成績    生年
0    千尋   1  85  90   B  2000
1    キキ   2  92  95   A  2000
2   ハウル   1  78  80   C  2000
3  ソフィー   3  95  98  A+  2000
4  アシタカ   2  88  85  B+  2000

#### 計算して新しい列を作成
`df["点数"] + df["出席"]`の結果は、（`Series + Series`）なので`Series`である。

In [12]:
df["合計点"] = df["点数"] + df["出席"]  # 計算されたSeriesの値が代入される

df

     名前  学年  点数  出席  成績    生年  合計点
0    千尋   1  85  90   B  2000  175
1    キキ   2  92  95   A  2000  187
2   ハウル   1  78  80   C  2000  158
3  ソフィー   3  95  98  A+  2000  193
4  アシタカ   2  88  85  B+  2000  173

#### # 修整

- 特定の値を修正

In [13]:
df.loc[0, "点数"] = 90

df

     名前  学年  点数  出席  成績    生年  合計点
0    千尋   1  90  90   B  2000  175
1    キキ   2  92  95   A  2000  187
2   ハウル   1  78  80   C  2000  158
3  ソフィー   3  95  98  A+  2000  193
4  アシタカ   2  88  85  B+  2000  173

- 特定範囲の値を修正

In [14]:
df.loc[df["点数"] < 80, "点数"] = 80

df

     名前  学年  点数  出席  成績    生年  合計点
0    千尋   1  90  90   B  2000  175
1    キキ   2  92  95   A  2000  187
2   ハウル   1  80  80   C  2000  158
3  ソフィー   3  95  98  A+  2000  193
4  アシタカ   2  88  85  B+  2000  173

##### * 原理

`df.loc[df["点数"] > 90, "点数"] = 99`  
→ 条件式の引数の位置には`Boolean Series型`が入る

`df.loc[pd.Series([False, True, False, True, False]), "点数"] = 99`

`df.loc[[False, True, False, True, False], "点数"] = 99`  
→ `リスト`が`Series`に自動で型変換される

#### `[]`演算子を使用すると列全体が修正される

In [15]:
df["合計点"] = 0

df

     名前  学年  点数  出席  成績    生年  合計点
0    千尋   1  90  90   B  2000    0
1    キキ   2  92  95   A  2000    0
2   ハウル   1  80  80   C  2000    0
3  ソフィー   3  95  98  A+  2000    0
4  アシタカ   2  88  85  B+  2000    0

#### # 削除

```py
- 行の削除：`drop("行ラベル", axis=0)`
```

- `axis=0`は行軸（縦方向 → 1つ以上の行を削除可能）

```py
- 列の削除：`drop("列ラベル", axis=1)`
```

- `axis=1`は列軸（横方向 → 1つ以上の列を削除可能）

In [16]:
# 「合計点」を列方向（axis=1）から削除

df.drop("合計点", axis=1)  # axisを省略すると0

     名前  学年  点数  出席  成績    生年
0    千尋   1  90  90   B  2000
1    キキ   2  92  95   A  2000
2   ハウル   1  80  80   C  2000
3  ソフィー   3  95  98  A+  2000
4  アシタカ   2  88  85  B+  2000

※ `drop()`の引数に`位置の値`を使用することはできない!

※ `特定位置の値`を削除することはできない → 値を空白、NaNなどの`欠損値に変更`することは可能

#### 情報確認

In [18]:
print(df.shape)

(5, 7)

In [19]:
print(df.columns)

Index(['名前', '学年', '点数', '出席', '成績', '生年', '合計点'], dtype='str')

In [ ]:
print(df.index)

RangeIndex(start=0, stop=5, step=1)

In [21]:
print(df.dtypes)

名前       str
学年     int64
点数     int64
出席     int64
成績       str
生年     int64
合計点    int64
dtype: object

## 2. 統計関連メソッド

#### 1) 全体の統計量

| 統計量 | 意味 |
|---|---|
| `count` | データ数 |
| `mean` | 平均 |
| `std` | 標準偏差 |
| `min` | 最小値 |
| `25%` | 第1四分位数 |
| `50%` | 中央値 |
| `75%` | 第3四分位数 |
| `max` | 最大値 |

In [24]:
df = pd.DataFrame({
    "名前": ["千尋", "キキ", "ハウル", "ソフィー", "アシタカ"],
    "学年": [1, 2, 1, 3, 2],
    "点数": [85, 92, 78, 95, 88],
    "出席": [90, 95, 80, 98, 85]
})

df

     名前  学年  点数  出席
0    千尋   1  85  90
1    キキ   2  92  95
2   ハウル   1  78  80
3  ソフィー   3  95  98
4  アシタカ   2  88  85

In [29]:
# 各列の欠損値を除いたデータ数を返す
print(df.count())

名前    5
学年    5
点数    5
出席    5
dtype: int64

In [30]:
# 数値型の列のみ合計を返す
print(df.sum(numeric_only=True))

学年      9
点数    438
出席    448
dtype: int64

In [31]:
# 数値型の列のみ平均値を返す
print(df.mean(numeric_only=True))

学年     1.8
点数    87.6
出席    89.6
dtype: float64

In [32]:
# 数値型の列のみ中央値を返す
print(df.median(numeric_only=True))

学年     2.0
点数    88.0
出席    90.0
dtype: float64

In [33]:
# 数値型の列のみ最小値を返す
print(df.min(numeric_only=True))

学年     1
点数    78
出席    80
dtype: int64

In [34]:
# 数値型の列のみ最大値を返す
print(df.max(numeric_only=True))

学年     3
点数    95
出席    98
dtype: int64

In [35]:
# 数値型の列のみ標準偏差を返す
print(df.std(numeric_only=True))

学年    0.836660
点数    6.580274
出席    7.300685
dtype: float64

In [36]:
# 「点数」列の最大値と最小値の差を返す
print(df["点数"].max() - df["点数"].min())

17

#### 数値型変数の統計量

In [38]:
# 数値型の列の基本統計量をまとめて表示する
df.describe()

            学年         点数         出席
count  5.00000   5.000000   5.000000
mean   1.80000  87.600000  89.600000
std    0.83666   6.580274   7.300685
min    1.00000  78.000000  80.000000
25%    1.00000  85.000000  85.000000
50%    2.00000  88.000000  90.000000
75%    2.00000  92.000000  95.000000
max    3.00000  95.000000  98.000000

`学年`の場合、カテゴリ型変数であるにもかかわらず`数値型変数`として設定されているため、統計量が出力される。

`学年`を`カテゴリ型`に変更すると、統計量には出力されない。

In [40]:
# 「学年」のデータ型をcategory型（カテゴリ型）に変換した結果を
# 再びdf["学年"]に保存し、dfの「学年」のデータ型を変更
df["学年"] = df["学年"].astype("category")

In [ ]:
df.info()  # データ型の確認

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   名前      5 non-null      str
 1   学年      5 non-null      category
 2   点数      5 non-null      int64
 3   出席      5 non-null      int64
dtypes: category(1), int64(2), str(1)
memory usage: 281.0 bytes

In [43]:
df

     名前 学年  点数  出席
0    千尋  1  85  90
1    キキ  2  92  95
2   ハウル  1  78  80
3  ソフィー  3  95  98
4  アシタカ  2  88  85