## 1. スケーリング

- スケーリングとは、**変数ごとの数値の大きさや範囲を同じような基準にそろえる**前処理方法である。
- スケーリングには複数の方法があり、`標準化（Standardization）`はその一つである。

<br>

### 1) スケーリングはいつ必要？

スケーリングはすべてのデータに必ず適用するものではなく、**アルゴリズムの特性**や**変数の単位・スケール**を確認して適用する。

<div style="display:flex; justify-content:flex-start;">
<table style="width:auto; border-collapse:collapse; text-align:left;">
<thead>
<tr>
<th style="padding:8px 14px;"><strong>アルゴリズム</strong></th>
<th style="padding:8px 14px;"><strong>スケーリング</strong></th>
</tr>
</thead>
<tbody>
<tr>
<td style="padding:8px 14px;"><strong>KNN</strong></td>
<td style="padding:8px 14px;"><strong>重要</strong></td>
</tr>
<tr>
<td style="padding:8px 14px;"><strong>K-means</strong></td>
<td style="padding:8px 14px;"><strong>重要</strong></td>
</tr>
<tr>
<td style="padding:8px 14px;"><strong>SVM</strong></td>
<td style="padding:8px 14px;"><strong>重要</strong></td>
</tr>
<tr>
<td style="padding:8px 14px;"><strong>ニューラルネットワーク</strong></td>
<td style="padding:8px 14px;">推奨</td>
</tr>
<tr>
<td style="padding:8px 14px;"><strong>線形回帰</strong></td>
<td style="padding:8px 14px;">状況による</td>
</tr>
<tr>
<td style="padding:8px 14px;"><strong>ロジスティック回帰</strong></td>
<td style="padding:8px 14px;">状況による</td>
</tr>
<tr>
<td style="padding:8px 14px;"><strong>Decision Tree</strong></td>
<td style="padding:8px 14px;">通常は不要</td>
</tr>
<tr>
<td style="padding:8px 14px;"><strong>Random Forest</strong></td>
<td style="padding:8px 14px;">通常は不要</td>
</tr>
<tr>
<td style="padding:8px 14px;"><strong>XGBoost</strong></td>
<td style="padding:8px 14px;">通常は不要</td>
</tr>
</tbody>
</table>
</div>

<br>

### 2) 代表的なスケーリング方法

<div style="display:flex; justify-content:flex-start;">
<table style="width:auto; border-collapse:collapse; text-align:left;">
<thead>
<tr>
<th style="padding:8px 14px;"><strong>方法</strong></th>
<th style="padding:8px 14px;"><strong>説明</strong></th>
<th style="padding:8px 14px;"><strong>代表的な sklearn</strong></th>
</tr>
</thead>
<tbody>
<tr>
<td style="padding:8px 14px;"><strong>標準化</strong></td>
<td style="padding:8px 14px;"><strong>平均0・標準偏差1</strong>を基準に変換</td>
<td style="padding:8px 14px;"><code>StandardScaler</code></td>
</tr>
<tr>
<td style="padding:8px 14px;"><strong>正規化</strong></td>
<td style="padding:8px 14px;">一定の範囲（主に<strong>0～1</strong>）に変換</td>
<td style="padding:8px 14px;"><code>MinMaxScaler</code></td>
</tr>
<tr>
<td style="padding:8px 14px;"><strong>ロバストスケーリング</strong></td>
<td style="padding:8px 14px;"><strong>中央値とIQR</strong>を利用し、外れ値の影響を抑える</td>
<td style="padding:8px 14px;"><code>RobustScaler</code></td>
</tr>
</tbody>
</table>
</div>

→ 距離や数値の大きさに影響を受けやすいアルゴリズムではスケーリングが重要で、木ベースのモデルでは通常その影響が小さい。

<br>

#### ※ 標準化（Standardization）の考え方

標準化とは、データを **平均0・標準偏差1** を基準とした値に変換する方法である。

$$
\Large\displaystyle z = \frac{x-\mu}{\sigma}
$$

- **x**：元のデータ
- **μ**：平均
- **σ**：標準偏差

<p style="color:#ff0000;">
<strong>Z-scoreは「平均から標準偏差の何倍離れているか」を表す。</strong>
</p>

<div style="display:flex; justify-content:flex-start;">
<table style="width:auto; border-collapse:collapse; text-align:left;">
<thead>
<tr>
<th style="padding:8px 14px;"><strong>Z-score</strong></th>
<th style="padding:8px 14px;"><strong>意味</strong></th>
</tr>
</thead>
<tbody>
<tr>
<td style="padding:8px 14px;"><strong>0</strong></td>
<td style="padding:8px 14px;">平均と同じ位置</td>
</tr>
<tr>
<td style="padding:8px 14px;"><strong>+1</strong></td>
<td style="padding:8px 14px;">平均より標準偏差1個分大きい</td>
</tr>
<tr>
<td style="padding:8px 14px;"><strong>+2</strong></td>
<td style="padding:8px 14px;">平均より標準偏差2個分大きい</td>
</tr>
<tr>
<td style="padding:8px 14px;"><strong>-1</strong></td>
<td style="padding:8px 14px;">平均より標準偏差1個分小さい</td>
</tr>
<tr>
<td style="padding:8px 14px;"><strong>-2</strong></td>
<td style="padding:8px 14px;">平均より標準偏差2個分小さい</td>
</tr>
</tbody>
</table>
</div>

<br>

#### 例）Z-scoreの考え方

**400, 500, 600**

- 平均：500
- 標準偏差：100
- Z-score：**-1, 0, 1**

→ 400は平均より標準偏差1個分小さく、  
500は平均と同じ、  
600は平均より標準偏差1個分大きい。

<br>

**4, 5, 6**

- 平均：5
- 標準偏差：1
- Z-score：**-1, 0, 1**

→ 数値の大きさや単位が異なっても、標準化すると**平均からどの程度離れているかを同じ尺度で比較できる**。

<br>

### 3) 標準化の実習

同じ **10%の変化** でも、変数ごとに単位や数値の大きさが異なると、KNNの距離計算では影響の大きさが大きく異なる。

→ 変化率が同じでも、**スケールが大きい変数ほど距離計算への影響が大きくなる**。  
→ そのため、KNNのような **距離ベースのアルゴリズムではスケーリングが重要** になる。

<br>

<div style="display:inline-block; min-width:420px; font-family:Consolas, 'Yu Gothic', monospace; line-height:27px; margin:4px 0 14px 0; color:#222;"><div style="background:#ffffff; padding:0 14px;">&nbsp;</div><div style="background:#e7e9eb; padding:0 14px;"><strong>身長</strong> = <span style="color:#ff5a1f;">160</span>cm</div><div style="background:#f4f5f6; padding:0 14px;"><strong>年収</strong> = <span style="color:#ff5a1f;">5,000,000</span>円</div><div style="background:#e7e9eb; padding:0 14px;"><strong>年齢</strong> = <span style="color:#ff5a1f;">30</span>歳</div></div>

#### ① 年収が10%増加した場合

身長と年齢は同じで、年収だけが **5,000,000円 → 5,500,000円** に変化する。

$$
\begin{aligned}
距離
&= \sqrt{(160-160)^2+(5{,}500{,}000-5{,}000{,}000)^2+(30-30)^2} \\
&= \sqrt{0+500{,}000^2+0} \\
&= \boxed{500{,}000}
\end{aligned}
$$

#### ② 年齢が10%増加した場合

身長と年収は同じで、年齢だけが **30歳 → 33歳** に変化する。

$$
\begin{aligned}
距離
&= \sqrt{(160-160)^2+(5{,}000{,}000-5{,}000{,}000)^2+(33-30)^2} \\
&= \sqrt{0+0+3^2} \\
&= \boxed{3}
\end{aligned}
$$

<div style="display:inline-block; min-width:720px; font-family:Consolas, 'Yu Gothic', monospace; line-height:27px; margin:4px 0 14px 0; color:#222;"><div style="background:#e7e9eb; padding:0 14px;"><span style="color:#ff4d6d;">年収（円）</span> → 数値が非常に大きい</div><div style="background:#f4f5f6; padding:0 14px;"><span style="color:#ff4d6d;">年齢（歳）</span> → 数値が小さい</div><div style="background:#e7e9eb; padding:0 14px 0 58px;">↓</div><div style="background:#f4f5f6; padding:0 14px;">距離計算</div><div style="background:#e7e9eb; padding:0 14px 0 58px;">↓</div><div style="background:#f4f5f6; padding:0 14px;">年収の影響が過度に大きくなる</div><div style="background:#e7e9eb; padding:0 14px 0 58px;">↓</div><div style="background:#f4f5f6; padding:0 14px;"><span style="color:#ff4d6d;">標準化</span>（StandardScaler）</div><div style="background:#e7e9eb; padding:0 14px 0 58px;">↓</div><div style="background:#f4f5f6; padding:0 14px;">各変数のスケールを同程度にそろえる</div></div>

<br>

#### # 変数ごとのスケールの違いが距離計算に与える影響を確認し、手動計算とStandardScalerを用いて標準化する。

##### (1) サンプルデータの作成

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.DataFrame({
    "身長(cm)": [160, 170, 180],
    "年収(円)": [5_000_000, 6_000_000, 8_000_000],
    "年齢(歳)": [30, 40, 50]
})

display(df)

   身長(cm)    年収(円)  年齢(歳)
0     160  5000000     30
1     170  6000000     40
2     180  8000000     50

<br>

##### (2) scikit-learnを使わずに標準化

In [2]:
mean = df.mean()
std = df.std(ddof=0)   # 母標準偏差

# df.std(ddof=1)       # 標本標準偏差

df_scaled = (df - mean) / std

display(df_scaled)

     身長(cm)     年収(円)     年齢(歳)
0 -1.224745 -1.069045 -1.224745
1  0.000000 -0.267261  0.000000
2  1.224745  1.336306  1.224745

→ 各変数について、**「データ − 平均」÷「標準偏差」** を計算し、平均0・標準偏差1を基準とした値に変換する。

<br>

##### (3) StandardScalerを使用して標準化

In [3]:
scaler = StandardScaler()

df_scaled = scaler.fit_transform(df)

df_scaled = pd.DataFrame(
    df_scaled,
    columns=df.columns
)

display(df_scaled)

     身長(cm)     年収(円)     年齢(歳)
0 -1.224745 -1.069045 -1.224745
1  0.000000 -0.267261  0.000000
2  1.224745  1.336306  1.224745

→ `StandardScaler`も母標準偏差（ddof=0）を使用するため、手動で計算した標準化結果と同じになる。

<br>

#### 4) 正規化の実習

正規化とは、最小値を **0**、最大値を **1** に合わせ、その他の値を最小値～最大値の範囲における比率として変換する方法である。

Min-Max正規化は **最小値と最大値を基準** に変換するため、外れ値が存在すると全体の変換結果が影響を受けやすい。

$$
\Large\displaystyle x'=\frac{x-\min(x)}{\max(x)-\min(x)}
$$

<div style="display:inline-block; min-width:520px; font-family:Consolas, 'Yu Gothic', monospace; line-height:27px; margin:4px 0 14px 0; color:#222;"><div style="background:#ffffff; padding:0 14px;">&nbsp;</div><div style="background:#e7e9eb; padding:0 14px;"><span style="color:#ff5a1f;">160</span> ───── <span style="color:#ff5a1f;">170</span> ───── <span style="color:#ff5a1f;">180</span></div><div style="background:#f4f5f6; padding:0 14px;">↓　　　　　　 ↓　　　　　　 ↓</div><div style="background:#e7e9eb; padding:0 14px;"><span style="color:#ff5a1f;">0</span>　　　　　 <span style="color:#ff5a1f;">0.5</span>　　　　　 <span style="color:#ff5a1f;">1</span></div><div style="background:#f4f5f6; padding:0 14px;">最小　　　　　　　　　　　 最大</div></div>

In [5]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df_scaled = scaler.fit_transform(df)

df_scaled = pd.DataFrame(
    df_scaled,
    columns=df.columns
)

display(df_scaled)

   身長(cm)     年収(円)  年齢(歳)
0     0.0  0.000000    0.0
1     0.5  0.333333    0.5
2     1.0  1.000000    1.0

→ 最小値が **0**、最大値が **1** となるように、各値が0～1の範囲へ変換される。

<br>

#### 5) ロバストスケーリングの実習

RobustScalerは、**中央値とIQR** を基準に変換し、外れ値の影響を抑えるスケーリング方法である。

$$
\Large\displaystyle x'=\frac{x-\mathrm{中央値}}{IQR}
$$

<p style="color:#ff0000; font-weight:700;">
ある値が中央値からIQRの何倍離れているかを表す。
</p>

In [6]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

df_scaled = scaler.fit_transform(df)

df_scaled = pd.DataFrame(
    df_scaled,
    columns=df.columns
)

display(df_scaled)

   身長(cm)     年収(円)  年齢(歳)
0    -1.0 -0.666667   -1.0
1     0.0  0.000000    0.0
2     1.0  1.333333    1.0

→ 中央値とIQRは平均や最小値・最大値より外れ値の影響を受けにくいため、**外れ値が多いデータに適している**。

<div style="display:inline-block; min-width:720px; font-family:Consolas, 'Yu Gothic', monospace; line-height:27px; margin:4px 0 14px 0; color:#222;"><div style="background:#ffffff; padding:0 14px;">&nbsp;</div><div style="background:#e7e9eb; padding:0 14px;"><strong>MinMaxScaler</strong></div><div style="background:#f4f5f6; padding:0 14px;">→ <strong><span style="color:#ff5a1f;">最小値・最大値</span></strong>を使用</div><div style="background:#e7e9eb; padding:0 14px;">→ <strong>外れ値に敏感</strong></div><div style="background:#f4f5f6; padding:0 14px;">&nbsp;</div><div style="background:#e7e9eb; padding:0 14px;"><strong>StandardScaler</strong></div><div style="background:#f4f5f6; padding:0 14px;">→ <strong><span style="color:#ff5a1f;">平均・標準偏差</span></strong>を使用</div><div style="background:#e7e9eb; padding:0 14px;">→ 「平均から標準偏差の何倍離れているか」を表す</div><div style="background:#f4f5f6; padding:0 14px;">→ <strong>外れ値の影響を受ける</strong></div><div style="background:#e7e9eb; padding:0 14px;">&nbsp;</div><div style="background:#f4f5f6; padding:0 14px;"><strong>RobustScaler</strong></div><div style="background:#e7e9eb; padding:0 14px;">→ <strong><span style="color:#ff5a1f;">中央値・IQR</span></strong>を使用</div><div style="background:#f4f5f6; padding:0 14px;">→ 「中央値からIQRの何倍離れているか」を表す</div><div style="background:#e7e9eb; padding:0 14px;">→ <strong>外れ値の影響を受けにくい</strong></div></div>

<br>

<p style="color:#ff0000; font-weight:700;">
標準化 vs ロバストスケーリング vs 正規化
</p>

#### # 同じデータに3つのスケーリング方法を適用し、変換結果の違いを比較する。

<br>

##### (1) サンプルデータの作成

In [7]:
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MinMaxScaler


df = pd.DataFrame({
    "身長(cm)": [160, 170, 180],
    "年収(円)": [5_000_000, 6_000_000, 8_000_000],
    "年齢(歳)": [30, 40, 50]
})

display(df)

   身長(cm)    年収(円)  年齢(歳)
0     160  5000000     30
1     170  6000000     40
2     180  8000000     50

<br>

##### (2) 標準化（StandardScaler）
-> **平均0・標準偏差1**を基準に変換する。

In [12]:
print('(2) 標準化（StandardScaler）')

scaler = StandardScaler()

df_standard = scaler.fit_transform(df)

df_standard = pd.DataFrame(
    df_standard,
    columns=df.columns
)

display(df_standard)

(2) 標準化（StandardScaler）

     身長(cm)     年収(円)     年齢(歳)
0 -1.224745 -1.069045 -1.224745
1  0.000000 -0.267261  0.000000
2  1.224745  1.336306  1.224745

<br>

##### (3) ロバストスケーリング（RobustScaler）

-> **中央値を0**とし、**IQR**を基準に変換する。

In [13]:
print('(3) ロバストスケーリング（RobustScaler）')

scaler = RobustScaler()

df_robust = scaler.fit_transform(df)

df_robust = pd.DataFrame(
    df_robust,
    columns=df.columns
)

display(df_robust)

(3) ロバストスケーリング（RobustScaler）

   身長(cm)     年収(円)  年齢(歳)
0    -1.0 -0.666667   -1.0
1     0.0  0.000000    0.0
2     1.0  1.333333    1.0

<br>

##### (4) 正規化（MinMaxScaler）

-> **最小値を0、最大値を1**として、0～1の範囲に変換する。

In [14]:
print('(4) 正規化（MinMaxScaler）')

scaler = MinMaxScaler()

df_minmax = scaler.fit_transform(df)

df_minmax = pd.DataFrame(
    df_minmax,
    columns=df.columns
)

display(df_minmax)

(4) 正規化（MinMaxScaler）

   身長(cm)     年収(円)  年齢(歳)
0     0.0  0.000000    0.0
1     0.5  0.333333    0.5
2     1.0  1.000000    1.0

<br>

※ **StandardScaler＝平均・標準偏差 / RobustScaler＝中央値・IQR / MinMaxScaler＝最小値・最大値** を基準に変換する。