## 1. 離散化

連続した数値を<strong>いくつかの区間に分ける</strong>こと。

<div style="display:inline-block; min-width:700px; font-family:Consolas, 'Yu Gothic', monospace; line-height:27px; margin:4px 0 14px 0; color:#222;"><div style="background:#ffffff; padding:0 14px;">&nbsp;</div><div style="background:#e7e9eb; padding:0 14px;">df["年齢"] = [<span style="color:#ff5a1f;">15, 23, 35, 47, 62, ...7, 10, 55, ...</span>]</div><div style="background:#f4f5f6; padding:0 14px;">&nbsp;</div><div style="background:#e7e9eb; padding:0 14px;">→ 区間に分けて <strong>カテゴリ名</strong>（カテゴリ化）を割り当てる</div><div style="background:#f4f5f6; padding:0 14px;"><span style="color:#ff5a1f;">0～19歳</span> → 青少年</div><div style="background:#e7e9eb; padding:0 14px;"><span style="color:#ff5a1f;">20～39歳</span> → 青年</div><div style="background:#f4f5f6; padding:0 14px;"><span style="color:#ff5a1f;">40～59歳</span> → 中年</div><div style="background:#e7e9eb; padding:0 14px;"><span style="color:#ff5a1f;">60歳以上</span> → 高齢者</div><div style="background:#f4f5f6; padding:0 14px;">&nbsp;</div><div style="background:#e7e9eb; padding:0 14px;">→ <strong>離散化＋カテゴリ化の結果</strong></div><div style="background:#f4f5f6; padding:0 14px;"><span style="color:#ff5a1f;">15</span> → 青少年</div><div style="background:#e7e9eb; padding:0 14px;"><span style="color:#ff5a1f;">23</span> → 青年</div><div style="background:#f4f5f6; padding:0 14px;"><span style="color:#ff5a1f;">35</span> → 青年</div><div style="background:#e7e9eb; padding:0 14px;"><span style="color:#ff5a1f;">47</span> → 中年</div><div style="background:#f4f5f6; padding:0 14px;"><span style="color:#ff5a1f;">62</span> → 高齢者</div><div style="background:#e7e9eb; padding:0 14px;">...</div></div>

<br>

#### ※ 離散化とカテゴリ化の違い

##### 1) 離散化（区間化）

<div style="display:inline-block; min-width:300px; font-family:Consolas, 'Yu Gothic', monospace; line-height:27px; margin:4px 0 14px 0; color:#222;"><div style="background:#e7e9eb; padding:0 14px;"><span style="color:#ff5a1f;">15</span> → <strong>0～20</strong></div><div style="background:#f4f5f6; padding:0 14px;"><span style="color:#ff5a1f;">25</span> → <strong>20～40</strong></div><div style="background:#e7e9eb; padding:0 14px;"><span style="color:#ff5a1f;">45</span> → <strong>40～60</strong></div><div style="background:#f4f5f6; padding:0 14px;"><span style="color:#ff5a1f;">70</span> → <strong>60～100</strong></div></div>

##### 2) カテゴリ化

<div style="display:inline-block; min-width:320px; font-family:Consolas, 'Yu Gothic', monospace; line-height:27px; margin:4px 0 14px 0; color:#222;"><div style="background:#e7e9eb; padding:0 14px;"><span style="color:#ff5a1f;">0～20</span> → 青少年</div><div style="background:#f4f5f6; padding:0 14px;"><span style="color:#ff5a1f;">20～40</span> → 青年</div><div style="background:#e7e9eb; padding:0 14px;"><span style="color:#ff5a1f;">40～60</span> → 中年</div><div style="background:#f4f5f6; padding:0 14px;"><span style="color:#ff5a1f;">60～100</span> → 高齢者</div></div>

##### 3) category dtype

<div style="display:inline-block; min-width:320px; font-family:Consolas, 'Yu Gothic', monospace; line-height:27px; margin:4px 0 14px 0; color:#222;"><div style="background:#ffffff; padding:0 14px;">&nbsp;</div><div style="background:#e7e9eb; padding:0 14px;">df["年齢"].dtype</div><div style="background:#f4f5f6; padding:0 14px;">&nbsp;</div></div>

<strong>区間化（離散化）</strong> → <strong>カテゴリ化</strong> → <strong>category dtypeとして保存</strong>

<p style="color:#ff0000;">
※ Pandasの <strong>cut()関数</strong> を使用した離散化（cut()はデフォルトで <strong>category dtype</strong> を返す）
</p>

<br>

## 2. sklearnのKBinsDiscretizerクラスを使用した離散化の実習

In [1]:
import pandas as pd
from sklearn.preprocessing import KBinsDiscretizer

# データ
df = pd.DataFrame({
    "年齢": [15, 23, 35, 47, 62]
})

display(df)

# 離散化
kb = KBinsDiscretizer(
    n_bins=3,             # 3つの区間
    encode="ordinal",     # 区間番号を数値で表現
    strategy="uniform"    # 等間隔で区間を分割
)

# strategyの指定方法は3種類
# uniform   → 区間の幅を均等にする
# quantile  → 各区間のデータ数がほぼ同じになるように分割
# kmeans    → K-Means方式で区間を決定

df["年齢_区間"] = kb.fit_transform(df[["年齢"]])

display(df)

   年齢
0  15
1  23
2  35
3  47
4  62

   年齢  年齢_区間
0  15    0.0
1  23    0.0
2  35    1.0
3  47    2.0
4  62    2.0

※ `uniform`では、年齢の範囲を<strong>同じ幅で3つの区間</strong>に分ける。  
`0.0 / 1.0 / 2.0` は年齢そのものではなく、<strong>所属する区間番号</strong>を表す。

- 15, 23 → 区間 0
- 35 → 区間 1
- 47, 62 → 区間 2