## 1. カテゴリデータのエンコーディング

<div style="display:flex; justify-content:flex-start;">
<table style="width:auto; border-collapse:collapse; text-align:left;">
<thead>
<tr>
<th style="padding:8px 14px;"><strong>方法</strong></th>
<th style="padding:8px 14px;"><strong>主な用途</strong></th>
<th style="padding:8px 14px;"><strong>例</strong></th>
<th style="padding:8px 14px;"><strong>特徴</strong></th>
</tr>
</thead>

<tbody>

<tr>
<td style="padding:8px 14px;"><strong>One-Hot Encoding</strong><br>（<code>OneHotEncoder</code>）</td>
<td style="padding:8px 14px;"><strong>順序のない</strong>入力特徴量 (<code>X</code>)</td>
<td style="padding:8px 14px;">地域：ソウル、釜山、大田</td>
<td style="padding:8px 14px;">カテゴリごとに列を作成し、該当するカテゴリを <strong>1</strong> で表す</td>
</tr>

<tr>
<td style="padding:8px 14px;"><strong>Ordinal Encoding</strong><br>（<code>OrdinalEncoder</code>）</td>
<td style="padding:8px 14px;"><strong>順序のある</strong>入力特徴量 (<code>X</code>)</td>
<td style="padding:8px 14px;">満足度：低い ＜ 普通 ＜ 高い</td>
<td style="padding:8px 14px;"><strong>指定した順序</strong>に従って数値へ変換する</td>
</tr>

<tr>
<td style="padding:8px 14px;"><strong>Label Encoding</strong><br>（<code>LabelEncoder</code>）</td>
<td style="padding:8px 14px;">分類問題の<strong>正解ラベル (<code>y</code>)</strong></td>
<td style="padding:8px 14px;">購入結果：キャンセル、維持、返品</td>
<td style="padding:8px 14px;">正解クラス名を数値で表す。<strong>入力特徴量には基本的に使用しない</strong></td>
</tr>

<tr>
<td style="padding:8px 14px;"><strong>Binary Encoding</strong></td>
<td style="padding:8px 14px;"><strong>カテゴリ数が非常に多い</strong>入力特徴量</td>
<td style="padding:8px 14px;">郵便番号、商品コード</td>
<td style="padding:8px 14px;">カテゴリを数値化した後、<strong>2進数の列</strong>で表す。通常は別途ライブラリが必要</td>
</tr>

<tr>
<td style="padding:8px 14px;"><strong>Target Encoding</strong></td>
<td style="padding:8px 14px;">カテゴリ数が多く、<strong>正解との関係</strong>を利用したい入力特徴量</td>
<td style="padding:8px 14px;">商品カテゴリ別の平均購入率</td>
<td style="padding:8px 14px;">各カテゴリを<strong>正解値の平均</strong>などで表す。学習データのリークに注意</td>
</tr>

<tr>
<td style="padding:8px 14px;"><strong>Count / Frequency Encoding</strong></td>
<td style="padding:8px 14px;"><strong>カテゴリ数が多い</strong>場合</td>
<td style="padding:8px 14px;">訪問した都市、商品コード</td>
<td style="padding:8px 14px;">カテゴリを<strong>出現回数または出現割合</strong>で表す</td>
</tr>

<tr>
<td style="padding:8px 14px;"><strong>Hashing Encoding</strong></td>
<td style="padding:8px 14px;">カテゴリ数が非常に多い、または<strong>新しいカテゴリが継続的に追加</strong>される場合</td>
<td style="padding:8px 14px;">ユーザーID、検索キーワード</td>
<td style="padding:8px 14px;"><strong>固定数の列</strong>にマッピングする。異なるカテゴリが同じ列に入る場合がある</td>
</tr>

<tr>
<td style="padding:8px 14px;"><strong>テキストベクトル化</strong><br>（<code>CountVectorizer</code>、<code>TfidfVectorizer</code>）</td>
<td style="padding:8px 14px;">文章、レビュー、検索キーワード</td>
<td style="padding:8px 14px;">「配送が速くて良いです」</td>
<td style="padding:8px 14px;"><strong>単語を基準</strong>として数値特徴量に変換する</td>
</tr>

</tbody>
</table>
</div>

<br>

## 2. 目的に応じたエンコーダーの選択

- 順序のない入力値：通常は <strong>OneHotEncoder</strong>
- 順序のある入力値：順序を直接指定できる <strong>OrdinalEncoder</strong>
- 教師あり学習の分類における正解ラベル y：必要に応じて <strong>LabelEncoder</strong>
- カテゴリ数が非常に多い列：<strong>Frequency Encoding</strong> や <strong>Target Encoding</strong> などを検討
- 文章やレビュー：<strong>CountVectorizer</strong> または <strong>TfidfVectorizer</strong>

<br>

#### 1) One-Hot Encoding

地域のように<strong>順序のない入力値</strong>を「ソウル = 0、釜山 = 1」のように変換すると、
モデルが数値間に順序があると誤って解釈する可能性がある。

- 説明変数 X には通常、<strong>OneHotEncoder</strong> を使用する。

- OneHotEncoderを使用すると、1つのカテゴリ変数から<strong>カテゴリ数に応じて新しい説明変数が作成される</strong>。

<br>

#### ※ One-Hot Encoding前のデータ

<div style="display:inline-block; min-width:260px; font-family:Consolas, 'Yu Gothic', monospace; line-height:27px; margin:4px 0 14px 0; color:#222;"><div style="background:#e7e9eb; padding:0 14px; font-weight:700;">地域</div><div style="background:#f4f5f6; padding:0 14px; font-weight:400;">ソウル</div><div style="background:#e7e9eb; padding:0 14px; font-weight:400;">釜山</div><div style="background:#f4f5f6; padding:0 14px; font-weight:400;">ソウル</div></div>

#### ※ One-Hot Encoding後のデータ

該当する地域なら **1**、該当しない地域なら **0**

<div style="display:inline-block; min-width:470px; font-family:Consolas, 'Yu Gothic', monospace; line-height:27px; margin:4px 0 14px 0; color:#222;"><div style="background:#e7e9eb; padding:0 14px;"><span style="display:inline-block; width:100px;"><strong>元の地域</strong></span><span style="display:inline-block; width:140px;"><strong>地域_釜山</strong></span><span style="display:inline-block; width:140px;"><strong>地域_ソウル</strong></span></div><div style="background:#f4f5f6; padding:0 14px;"><span style="display:inline-block; width:100px;"><strong>ソウル</strong></span><span style="display:inline-block; width:140px; color:#ff5a1f;">0</span><span style="display:inline-block; width:140px; color:#ff5a1f;">1</span></div><div style="background:#e7e9eb; padding:0 14px;"><span style="display:inline-block; width:100px;"><strong>釜山</strong></span><span style="display:inline-block; width:140px; color:#ff5a1f;">1</span><span style="display:inline-block; width:140px; color:#ff5a1f;">0</span></div><div style="background:#f4f5f6; padding:0 14px;"><span style="display:inline-block; width:100px;"><strong>ソウル</strong></span><span style="display:inline-block; width:140px; color:#ff5a1f;">0</span><span style="display:inline-block; width:140px; color:#ff5a1f;">1</span></div></div>

<br>

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({
    '色': ['赤', '青', '緑', '赤', '緑'],
    '価格': [1000, 1500, 2000, 1200, 1800]
})

display(df)

encoder = OneHotEncoder(
    sparse_output=False
)  # sparse_output=False：NumPy配列で返す / True：疎行列で返す

result = encoder.fit_transform(df[['色']])

# エンコーディング後の列名を取得
columns = encoder.get_feature_names_out(['色'])

# エンコーディング結果を新しい特徴量として追加
df[columns] = result

display(df)

   色    価格
0  赤  1000
1  青  1500
2  緑  2000
3  赤  1200
4  緑  1800

   色    価格  色_緑  色_赤  色_青
0  赤  1000  0.0  1.0  0.0
1  青  1500  0.0  0.0  1.0
2  緑  2000  1.0  0.0  0.0
3  赤  1200  0.0  1.0  0.0
4  緑  1800  1.0  0.0  0.0

<br>

#### 2) Ordinal Encoding

満足度のように、カテゴリに<strong>順序がある場合</strong>に使用する。

<div style="display:inline-block; min-width:300px; font-family:Consolas, 'Yu Gothic', monospace; line-height:27px; margin:4px 0 14px 0; color:#222;"><div style="background:#e7e9eb; padding:0 14px;"><strong>低い</strong> ＜ <strong>普通</strong> ＜ <strong>高い</strong></div></div>

<div style="display:inline-block; min-width:300px; font-family:Consolas, 'Yu Gothic', monospace; line-height:27px; margin:4px 0 14px 0; color:#222;"><div style="background:#e7e9eb; padding:0 14px;"><strong>低い</strong> → <span style="color:#ff5a1f;">0</span></div><div style="background:#f4f5f6; padding:0 14px;"><strong>普通</strong> → <span style="color:#ff5a1f;">1</span></div><div style="background:#e7e9eb; padding:0 14px;"><strong>高い</strong> → <span style="color:#ff5a1f;">2</span></div></div>

<br>

#### 例）

In [2]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

df = pd.DataFrame({
    '満足度': ['高い', '低い', '普通', '高い', '普通'],
    '価格': [1000, 1500, 2000, 1200, 1800]
})

display(df)

encoder = OrdinalEncoder(
    categories=[['低い', '普通', '高い']]
)

# エンコーディング結果を新しい特徴量として追加
df['満足度_エンコード'] = encoder.fit_transform(df[['満足度']])

display(df)

  満足度    価格
0  高い  1000
1  低い  1500
2  普通  2000
3  高い  1200
4  普通  1800

  満足度    価格  満足度_エンコード
0  高い  1000        2.0
1  低い  1500        0.0
2  普通  2000        1.0
3  高い  1200        2.0
4  普通  1800        1.0

<br>

#### 3) Label Encoding

分類問題の<strong>正解ラベル y</strong>のクラス名を数値に変換するときに、LabelEncoderを使用する。

- LabelEncoderは、<strong>入力特徴量 X のカテゴリ列を変換するためのものではない</strong>。

- OrdinalEncoderとは異なり、LabelEncoderが自動的に割り当てる数値には<strong>順序の意味はない</strong>。

- ただし、入力特徴量 X に使用すると、モデルによっては数値を順序や距離として解釈する可能性があるため、
X のカテゴリ列には通常<strong>One-Hot Encoding</strong>を使用する。

<div style="display:inline-block; min-width:300px; font-family:Consolas, 'Yu Gothic', monospace; line-height:27px; margin:4px 0 14px 0; color:#222;"><div style="background:#e7e9eb; padding:0 14px;"><strong>タイ、ワカサギ、ボラ</strong></div></div>

<div style="display:inline-block; min-width:300px; font-family:Consolas, 'Yu Gothic', monospace; line-height:27px; margin:4px 0 14px 0; color:#222;"><div style="background:#e7e9eb; padding:0 14px;"><strong>タイ</strong> → <span style="color:#ff5a1f;">0</span></div><div style="background:#f4f5f6; padding:0 14px;"><strong>ワカサギ</strong> → <span style="color:#ff5a1f;">1</span></div><div style="background:#e7e9eb; padding:0 14px;"><strong>ボラ</strong> → <span style="color:#ff5a1f;">2</span></div></div>

<br>

#### 例）

In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame({
    '長さ': [30, 35, 40, 45, 50],
    '重さ': [300, 350, 400, 450, 500],
    '種類': ['Bream', 'Smelt', 'Bream', 'Smelt', 'Bream']
})

display(df)

encoder = LabelEncoder()

# 正解ラベルを数値に変換して新しい特徴量を作成
df['種類_エンコード'] = encoder.fit_transform(df['種類'])

display(df)

   長さ   重さ     種類
0  30  300  Bream
1  35  350  Smelt
2  40  400  Bream
3  45  450  Smelt
4  50  500  Bream

   長さ   重さ     種類  種類_エンコード
0  30  300  Bream         0
1  35  350  Smelt         1
2  40  400  Bream         0
3  45  450  Smelt         1
4  50  500  Bream         0