- `groupby()`は、特定の列で同じ値を持つデータをグループ化し、  
グループごとに`平均・合計・件数`などを計算するときに使用する。

- SQLの`GROUP BY`とほぼ同じ考え方である。

In [2]:
import pandas as pd


df = pd.DataFrame({
    "部署": ["営業", "営業", "開発", "開発", "人事"],
    "名前": ["千尋", "ハウル", "ソフィー", "アシタカ", "キキ"],
    "売上": [100, 150, 200, 250, 120]
})

display(df)

   部署    名前   売上
0  営業    千尋  100
1  営業   ハウル  150
2  開発  ソフィー  200
3  開発  アシタカ  250
4  人事    キキ  120

<br>

#### - グループごとの平均を求める

In [3]:
result = df.groupby("部署")["売上"].mean()

display(result)

部署
人事    120.0
営業    125.0
開発    225.0
Name: 売上, dtype: float64

<br>

#### # groupby()で使用する主な集計メソッド

`groupby()`でグループ化した後、`sum()`・`mean()`・`count()`・`max()`・`min()`などを使用して集計できる。

In [5]:
# 部署別の売上合計
display(df.groupby("部署")["売上"].sum())

部署
人事    120
営業    250
開発    450
Name: 売上, dtype: int64

<br>

In [6]:
# 部署別の売上平均
display(df.groupby("部署")["売上"].mean())

部署
人事    120.0
営業    125.0
開発    225.0
Name: 売上, dtype: float64

<br>

In [7]:
# 部署別のデータ件数
display(df.groupby("部署")["売上"].count())

部署
人事    1
営業    2
開発    2
Name: 売上, dtype: int64

<br>

In [8]:
# 部署別の最大売上
display(df.groupby("部署")["売上"].max())

部署
人事    120
営業    150
開発    250
Name: 売上, dtype: int64

<br>

In [9]:
# 部署別の最小売上
display(df.groupby("部署")["売上"].min())

部署
人事    120
営業    100
開発    200
Name: 売上, dtype: int64

<br>

<span style="color:red; font-weight:bold;">
- groupby(), transform()メソッドを利用したカテゴリ別派生変数の追加例)
</span>

In [10]:
import pandas as pd


df = pd.DataFrame({
    "部署": ["営業", "営業", "開発", "開発", "人事"],
    "名前": ["千尋", "ハウル", "ソフィー", "アシタカ", "キキ"],
    "売上": [100, 150, 200, 250, 120]
})

display(df)

   部署    名前   売上
0  営業    千尋  100
1  営業   ハウル  150
2  開発  ソフィー  200
3  開発  アシタカ  250
4  人事    キキ  120

<br>

`groupby().mean()`はグループごとに`1つの結果`だけを返すが、`transform("mean")`は`元の行数と同じ数の結果`を返す。

In [ ]:
# 部署ごとの平均売上を元の行数と同じ形で返す
df.groupby("部署")["売上"].transform("mean")

0    125.0
1    125.0
2    225.0
3    225.0
4    120.0
Name: 売上, dtype: float64

<br>

In [14]:
# 上の結果を新しい派生変数としてDataFrameに追加
df["部署別平均売上"] = df.groupby("部署")["売上"].transform("mean")

display(df)

   部署    名前   売上  部署別平均売上
0  営業    千尋  100    125.0
1  営業   ハウル  150    125.0
2  開発  ソフィー  200    225.0
3  開発  アシタカ  250    225.0
4  人事    キキ  120    120.0