> **📌 表示について**
>
> 本ノートでは、`コードおよび出力結果の可読性を高めるため`、一部の表示形式を整理・再構成している。  
> 出力結果をMarkdownで別途まとめている箇所もあるが、`値や処理内容の意味は実際の実行結果に基づいている`。

In [8]:
print()

※ Series型のすべてのメソッドリファレンスは以下で確認

https://pandas.pydata.org/docs/reference/series.html

<br>

DataFrame = 複数のSeriesが集まった2次元データ構造  
Series = DataFrameから1つの列を選択した1次元データ構造

<span style="color:red;">df["列名"] → Seriesを返す</span>  
<span style="color:red;">df[["列名"]] → DataFrameを返す</span>

In [5]:
import pandas as pd

df = pd.DataFrame({
    "名前": ["千尋", "キキ", "ハウル"],
    "点数": [80, 90, 75]
})

In [6]:
# 1列を選択 → Series
s = df["点数"]

display(s)
display(type(s))

0    80
1    90
2    75
Name: 点数, dtype: int64

pandas.Series

In [7]:
# 1列をリスト形式で選択 → DataFrame
df2 = df[["点数"]]

display(df2)
display(type(df2))

   点数
0  80
1  90
2  75

pandas.DataFrame

<br>

<span style="color:red;">
※ <strong>DataFrameは複数のSeriesが集まった2次元データ構造</strong>であるため、Seriesで使用するメソッドと、DataFrameで使用するメソッドは非常に似ている。
</span>

#### ※ SeriesとDataFrameの主な対応メソッド

<table align="left">
  <thead>
    <tr>
      <th>機能</th>
      <th><code>Series</code></th>
      <th><code>DataFrame</code></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>欠損値の確認</td>
      <td>s.isna()</td>
      <td>df.isna()</td>
    </tr>
    <tr>
      <td>欠損値の個数</td>
      <td>s.isna().sum()</td>
      <td>df.isna().sum()</td>
    </tr>
    <tr>
      <td>欠損値の削除</td>
      <td>s.dropna()</td>
      <td>df.dropna()</td>
    </tr>
    <tr>
      <td>欠損値の置換</td>
      <td>s.fillna(0)</td>
      <td>df.fillna(0)</td>
    </tr>
    <tr>
      <td>並べ替え</td>
      <td>s.sort_values()</td>
      <td>df.sort_values()</td>
    </tr>
    <tr>
      <td>重複の削除</td>
      <td>s.drop_duplicates()</td>
      <td>df.drop_duplicates()</td>
    </tr>
    <tr>
      <td>統計</td>
      <td>s.mean()</td>
      <td>df.mean()</td>
    </tr>
    <tr>
      <td>累積最大値</td>
      <td>s.cummax()</td>
      <td>df.cummax()</td>
    </tr>
    <tr>
      <td>累積合計</td>
      <td>s.cumsum()</td>
      <td>df.cumsum()</td>
    </tr>
    <tr>
      <td>値の個数</td>
      <td>s.value_counts()</td>
      <td>df.value_counts()</td>
    </tr>
    <tr>
      <td>型変換</td>
      <td>s.astype()</td>
      <td>df.astype()</td>
    </tr>
    <tr>
      <td>apply()</td>
      <td>値 / 要素に適用</td>
      <td>行 / 列単位で適用可能</td>
    </tr>
  </tbody>
</table>

<br clear="left">

<br>

## 1. 実習用データセット

In [2]:
import pandas as pd
import numpy as np


df = pd.DataFrame({
    "従業員ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "名前": ["千尋", "キキ", "ハウル", "ソフィー",
            "アシタカ", "サン", "ポルコ", "ナウシカ"],
    "部署": ["開発", "営業", "開発", "人事",
            "営業", "開発", "営業", "人事"],
    "性別": ["男", "女", "男", "女", "男", "女", "女", "男"],
    "売上": [550, 320, np.nan, 780, 1200, 650, 920, np.nan],
    "勤務時間": [160, 172, 168, 155, 180, 150, 172, 158],
    "等級": ["B", "A", "B", "C", "A", "C", "A", None],
    "入社年度": [2020, 2019, 2021, 2022, 2018, 2023, 2019, 2022]
})

display(df)

   従業員ID    名前  部署 性別      売上  勤務時間   等級  入社年度
0    101    千尋  開発  男   550.0   160    B  2020
1    102    キキ  営業  女   320.0   172    A  2019
2    103   ハウル  開発  男     NaN   168    B  2021
3    104  ソフィー  人事  女   780.0   155    C  2022
4    105  アシタカ  営業  男  1200.0   180    A  2018
5    106    サン  開発  女   650.0   150    C  2023
6    107   ポルコ  営業  女   920.0   172    A  2019
7    108  ナウシカ  人事  男     NaN   158  NaN  2022

<br>

## 2. Seriesメソッドの分類

<div style="background-color:#f4f5f5; padding:0; color:#111111; font-family:monospace;">

<div style="background-color:#eaecee; padding:7px 16px;">
［データ探索］
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
head → tail → info → describe
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
&nbsp;
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
［統計］
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
mean / median / mode
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
sum / min / max
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
std / var
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
count / quantile
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
&nbsp;
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
［カテゴリデータ］
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
unique → nunique → value_counts
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
&nbsp;
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
［欠損値］
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
isna / isnull
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
notna / notnull
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
↓
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
fillna / dropna
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
&nbsp;
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
［データ変換］
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
apply / map / replace
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
where / mask
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
&nbsp;
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
［時系列・変化］
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
shift → diff → pct_change
</div>

</div>

<br>

## 3. 実習

#### 1) 基本情報

In [ ]:
s = df["売上"]

display("sの型:", type(s))


display(df["売上"].head(2))  # デフォルト値 5
display(df["売上"].tail(2))

```text
【Series型】

sの型: <class 'pandas.Series'>
--------------------------------------------------

【先頭・末尾データ】

- head(2)
0    550.0
1    320.0
Name: 売上, dtype: float64

- tail(2)
6    920.0
7      NaN
Name: 売上, dtype: float64
```

In [ ]:
print()

In [ ]:
display(df["売上"].info())
display(df["売上"].describe())
display(df["等級"].describe())

```text
【基本情報・記述統計量】

<class 'pandas.Series'>
RangeIndex: 8 entries, 0 to 7
Series name: 売上
Non-Null Count  Dtype  
--------------  -----  
6 non-null      float64
dtypes: float64(1)
memory usage: 196.0 bytes

- 売上
count       6.000000
mean      736.666667
std       305.330422
min       320.000000
25%       575.000000
50%       715.000000
75%       885.000000
max      1200.000000
Name: 売上, dtype: float64

- 等級
count     7
unique    3
top       A
freq      3
Name: 等級, dtype: object
```

In [ ]:
print()

#### 2) 統計

In [ ]:
display("平均:", df["売上"].mean())
display("中央値:", df["売上"].median())

# カテゴリ型 - 最頻値は頻度が同じ場合、
# 2つ以上を返す必要があるためSeries型で返す
display("最頻値:", df["等級"].mode())
display("最頻値:", df["性別"].mode())


display("合計:", df["売上"].sum())
display("最大値:", df["売上"].max())
display("最小値:", df["売上"].min())


display("分散:", df["売上"].var())
display("標準偏差:", df["売上"].std())


display("第1四分位数:", df["売上"].quantile(0.25))
display("第2四分位数:", df["売上"].quantile(0.50))
display("第3四分位数:", df["売上"].quantile(0.75))

```text
【代表値】
- 平均: 736.6666666666666
- 中央値: 715.0
--------------------------------------------------
【最頻値】
- 等級: A
- 性別: 女 男
--------------------------------------------------
【合計・最大・最小】
- 合計: 4420.0
- 最大値: 1200.0
- 最小値: 320.0
--------------------------------------------------
【分散・標準偏差】
- 分散: 93226.66666666666
- 標準偏差: 305.33042211130333
--------------------------------------------------
【四分位数】
- 第1四分位数: 575.0
- 第2四分位数: 715.0
- 第3四分位数: 885.0
```

In [ ]:
# データ数
# Series.count()メソッド vs len()関数

# NaNを除外してデータ数を確認
display(df["売上"].count())  

# NaNを含めて全体のデータ数を確認
display(len(df["売上"]))

np.int64(6)

8

In [ ]:
print()

#### 3) 一意な値 - カテゴリ型データで主に使用

In [ ]:
# 性別の一意な値を確認
display(df["性別"].unique()) 

# 部署の一意な値を確認
display(df["部署"].unique())

```text
【一意な値】

- 性別
<StringArray>
['男', '女']
Length: 2, dtype: str

- 部署
<StringArray>
['開発', '営業', '人事']
Length: 3, dtype: str
```

In [ ]:
# 性別の一意な値の個数を確認
display(df["性別"].nunique()) 

# 部署の一意な値の個数を確認
display(df["部署"].nunique())

```text
【一意な値の個数】

- 性別
2

- 部署
3
```

In [ ]:
print()

#### 4) 頻度 - カテゴリ型データで主に使用

In [ ]:
# 性別ごとの出現回数を確認
display(df["性別"].value_counts()) 

# 部署ごとの出現回数を確認
display(df["部署"].value_counts())

```text
【性別】

性別
男    4
女    4
Name: count, dtype: int64


【部署】

部署
開発    3
営業    3
人事    2
Name: count, dtype: int64
```

In [ ]:
print()

#### 5) 欠損値 - 欠損値の場合True

In [ ]:
# 売上の欠損値をTrueで確認
display(df["売上"].isna()) 

# isna()と同様に、売上の欠損値をTrueで確認
display(df["売上"].isnull())

```text
【isna()】

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
Name: 売上, dtype: bool


【isnull()】

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
Name: 売上, dtype: bool
```

In [ ]:
print()

In [ ]:
# 売上の欠損値ではない値をTrueで確認
display(df["売上"].notna()) 

# notna()と同様に、売上の欠損値ではない値をTrueで確認
display(df["売上"].notnull())

```text
【notna()】

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: 売上, dtype: bool


【notnull()】

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: 売上, dtype: bool
```

In [ ]:
print()

In [ ]:
# 欠損値を置換

sales = df["売上"]

sales = sales.fillna(sales.mean()) 

display(sales)

```text
【fillna() - 欠損値を置換】

0     550.000000
1     320.000000
2     736.666667
3     780.000000
4    1200.000000
5     650.000000
6     920.000000
7     736.666667
Name: 売上, dtype: float64
```

In [ ]:
print()

In [ ]:
# 欠損値を削除

sales = df["売上"]

sales_clean = sales.dropna() 

display(sales_clean)

```text
【dropna() - 欠損値を削除】

0     550.0
1     320.0
3     780.0
4    1200.0
5     650.0
6     920.0
Name: 売上, dtype: float64
```

In [ ]:
print()

#### 6) 並べ替え - 欠損値は昇順・降順に関係なく最後

In [ ]:
# 売上を降順に並べ替え
display(df["売上"].sort_values(ascending=False))

# 売上を昇順に並べ替え
display(df["売上"].sort_values())

```text
【売上 - 降順】

4    1200.0
6     920.0
3     780.0
5     650.0
0     550.0
1     320.0
2       NaN
7       NaN
Name: 売上, dtype: float64


【売上 - 昇順】

1     320.0
0     550.0
5     650.0
3     780.0
6     920.0
4    1200.0
2       NaN
7       NaN
Name: 売上, dtype: float64
```

In [ ]:
print()

In [ ]:
# 文字列も並べ替え
display(df["名前"].sort_values())

# 値ではなくインデックス順に並べ替え
display(df["名前"].sort_index(ascending=False))

```text
【名前 - 値で並べ替え】

4    アシタカ
1      キキ
5      サン
3    ソフィー
7    ナウシカ
2     ハウル
6     ポルコ
0      千尋
Name: 名前, dtype: str


【名前 - インデックス降順】

7    ナウシカ
6     ポルコ
5      サン
4    アシタカ
3    ソフィー
2     ハウル
1      キキ
0      千尋
Name: 名前, dtype: str
```

In [ ]:
print()

#### 7) 文字列 - str属性を使用

In [ ]:
# 名前に「キ」が含まれているか確認
display(df["名前"].str.contains("キ"))

```text
【str.contains("キ")】

0    False
1     True
2    False
3    False
4    False
5    False
6    False
7    False
Name: 名前, dtype: bool
```

In [ ]:
print()

In [ ]:
names1 = pd.Series([
    " 千尋 ",
    " キキ",
    "ハ ウル ",
    " ソフィー "
])


# 前後の空白を削除
names2 = names1.str.strip()
display(names2)


# 文字列内も含め、すべての空白を削除
names3 = names1.str.replace(" ", "")
display(names3)

```text
【str.strip() - 前後の空白を削除】

0       千尋
1       キキ
2     ハ ウル
3     ソフィー
dtype: str


【str.replace(" ", "") - すべての空白を削除】

0      千尋
1      キキ
2     ハウル
3    ソフィー
dtype: str
```

In [ ]:
print()

#### 8) 型変換

In [ ]:
# 従業員IDのデータ型を確認
employee_id = df["従業員ID"]
print(employee_id.info())

print()

# 従業員IDを文字列型に変換
employee_id = employee_id.astype(str)
print(employee_id.info())

```text
【従業員ID - 変換前】

<class 'pandas.Series'>
RangeIndex: 8 entries, 0 to 7
Series name: 従業員ID
Non-Null Count  Dtype
--------------  -----
8 non-null      int64
dtypes: int64(1)
memory usage: 196.0 bytes
None


【従業員ID - str型に変換後】

<class 'pandas.Series'>
RangeIndex: 8 entries, 0 to 7
Series name: 従業員ID
Non-Null Count  Dtype
--------------  -----
8 non-null      str
dtypes: str(1)
memory usage: 196.0 bytes
None
```

In [ ]:
print()

In [ ]:
# 性別のデータ型を確認
gender = df["性別"]
print(gender.info())

print()

# object/string型からcategory型に変換
gender = gender.astype("category")
print(gender.info())

```text
【性別 - 変換前】

<class 'pandas.Series'>
RangeIndex: 8 entries, 0 to 7
Series name: 性別
Non-Null Count  Dtype
--------------  -----
8 non-null      str  
dtypes: str(1)
memory usage: 196.0 bytes
None


【性別 - category型に変換後】

<class 'pandas.Series'>
RangeIndex: 8 entries, 0 to 7
Series name: 性別
Non-Null Count  Dtype   
--------------  -----   
8 non-null      category
dtypes: category(1)
memory usage: 156.0 bytes
None
```

In [ ]:
print()

In [ ]:
# 数値型に変換

sales = pd.Series(["850", "920", "780", "誤った値"])

# sales = pd.to_numeric(sales)  ERROR

# errors="coerce" → 数値に変換できない値をNaNに変換
sales = pd.to_numeric(sales, errors="coerce")
display(sales)

sales = pd.Series(["A", "B", "C"])
sales = pd.to_numeric(sales, errors="coerce")
display(sales)

```text
【数値に変換できない値をNaNに変換】

0    850.0
1    920.0
2    780.0
3      NaN
dtype: float64


【すべて数値に変換できない場合】

0    NaN
1    NaN
2    NaN
dtype: float64
```

In [ ]:
print()

#### 9) 条件処理

In [ ]:
# where() → 条件がFalseの値を変更する  
# 売上が800以上の値はそのまま残し、800未満の値はNaNにする。
result = df["売上"].where(df["売上"] >= 800)
display(result)


# mask() → 条件がTrueの値を変更する
# 売上が800未満の値を0に変更する。
result = df["売上"].mask(df["売上"] < 800, 0)
display(result)

```text
【where() - 800以上は元の値、800未満はNaN】

0       NaN
1       NaN
2       NaN
3       NaN
4    1200.0
5       NaN
6     920.0
7       NaN
Name: 売上, dtype: float64


【mask() - 800未満を0に変更】

0       0.0
1       0.0
2       NaN
3       0.0
4    1200.0
5       0.0
6     920.0
7       NaN
Name: 売上, dtype: float64
```

In [ ]:
print()

#### 10) 重複の確認・重複の削除

In [ ]:
# 部署の各値が重複しているか確認
display(df["部署"].duplicated())


# 部署の重複した値を削除
unique_department = df["部署"].drop_duplicates()
display(unique_department)

```text
【duplicated()】

0    False
1    False
2     True
3    False
4     True
5     True
6     True
7     True
Name: 部署, dtype: bool


【drop_duplicates()】

0    開発
1    営業
3    人事
Name: 部署, dtype: str
```

In [ ]:
print()

#### 11) データ値の変更

In [ ]:
# 特定の値のみ変更
department_eng1 = df["部署"].replace({
    "開発": "Development"
})

display(department_eng1)

```text
【replace() - 「開発」のみ変更】

0    Development
1             営業
2    Development
3             人事
4             営業
5    Development
6             営業
7             人事
Name: 部署, dtype: str
```

In [ ]:
print()

In [ ]:
# Series全体を変換
# マッピングされていない値はNaNに変換されるため、全体を変換する場合に使用
department_eng2 = df["部署"].map({
    "開発": "Development"
})

display(department_eng2)

```text
【map() - マッピングされていない値はNaN】

0    Development
1            NaN
2    Development
3            NaN
4            NaN
5    Development
6            NaN
7            NaN
Name: 部署, dtype: str
```

In [ ]:
print()

In [ ]:
# apply()メソッドに関数を引数として渡す（高階関数）
def sales_grade(value):
    # valueはSeriesではないため、value.isna()は使用できない
    # pd.isna(値)を使用する
    if pd.isna(value):
        return "未集計"
    elif value >= 1000:
        return "優秀"
    elif value >= 800:
        return "普通"
    else:
        return "低い"


# Seriesの各値にsales_grade関数を順番に適用
grade = df["売上"].apply(sales_grade)
display(grade)

```text
【apply() - 売上を評価】

0     低い
1     低い
2    未集計
3     低い
4     優秀
5     低い
6     普通
7    未集計
Name: 売上, dtype: str
```

In [ ]:
print()

#### 12) 累積

In [ ]:
# 累積合計 - NaNを除外
display(df["売上"].cumsum())

0     550.0
1     870.0
2       NaN
3    1650.0
4    2850.0
5    3500.0
6    4420.0
7       NaN
Name: 売上, dtype: float64

0    1.1000
1    1.3200
2    1.1880
3    1.3068
dtype: float64

In [ ]:
print()

In [48]:
# スライディング比較を行い、大きい値を残す - NaNを除外
display(df["売上"].cummax())

0     550.0
1     550.0
2       NaN
3     780.0
4    1200.0
5    1200.0
6    1200.0
7       NaN
Name: 売上, dtype: float64

In [ ]:
print()

In [50]:
# スライディング比較を行い、小さい値を残す - NaNを除外
display(df["売上"].cummin())

0    550.0
1    320.0
2      NaN
3    320.0
4    320.0
5    320.0
6    320.0
7      NaN
Name: 売上, dtype: float64

In [ ]:
print()

In [51]:
# 累積積
growth = pd.Series([1.1, 1.2, 0.9, 1.1])
display(growth.cumprod())

0    1.1000
1    1.3200
2    1.1880
3    1.3068
dtype: float64

In [ ]:
print()

#### 13) 時系列データにシフト演算

In [3]:
# 値の移動：1つ分移動（0番目の値はNaNに置換）
display(df["売上"].shift())

# 値の差：直前の値との差（0番目は前の値がないためNaN）
display(df["売上"].diff())

0       NaN
1     550.0
2     320.0
3       NaN
4     780.0
5    1200.0
6     650.0
7     920.0
Name: 売上, dtype: float64

0      NaN
1   -230.0
2      NaN
3      NaN
4    420.0
5   -550.0
6    270.0
7      NaN
Name: 売上, dtype: float64

In [ ]:
print()

In [4]:
# 直前の値と比較して何%増加・減少したか
# 100 → 110の場合 0.1（10%）
# 100 → 90の場合 -0.1（-10%）
# 100 → 100の場合 0
display(df["売上"].pct_change())

0         NaN
1   -0.418182
2         NaN
3         NaN
4    0.538462
5   -0.458333
6    0.415385
7         NaN
Name: 売上, dtype: float64

In [ ]:
print()

#### 14) その他

In [5]:
# 値が含まれているか確認 isin()
display(df["性別"].isin(["male"]))

display(df["性別"].isin(["男"]))

display(df["性別"].isin(["男", "女"]))

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: 性別, dtype: bool

0     True
1    False
2     True
3    False
4     True
5    False
6    False
7     True
Name: 性別, dtype: bool

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
Name: 性別, dtype: bool

In [ ]:
print()

In [6]:
# 無作為抽出 sample()
display(df["名前"].sample(3, random_state=42))

# random_stateの値が同じ場合、同じランダムアルゴリズムが適用される → 同じ結果
display(df["名前"].sample(3, random_state=42))

display(df["名前"].sample(3, random_state=0))

1    キキ
5    サン
0    千尋
Name: 名前, dtype: str

1    キキ
5    サン
0    千尋
Name: 名前, dtype: str

6    ポルコ
2    ハウル
1     キキ
Name: 名前, dtype: str

In [ ]:
print()

In [7]:
# Seriesを確認

name = df["名前"]

display(type(name))
display(name)

print()

# SeriesをDataFrameに変換
name_df = name.to_frame()

display(type(name_df))
display(name_df)

pandas.Series

0      千尋
1      キキ
2     ハウル
3    ソフィー
4    アシタカ
5      サン
6     ポルコ
7    ナウシカ
Name: 名前, dtype: str

pandas.DataFrame

     名前
0    千尋
1    キキ
2   ハウル
3  ソフィー
4  アシタカ
5    サン
6   ポルコ
7  ナウシカ

In [ ]:
print()

In [ ]:
# コピー・equals()


# 元のSeriesをコピー
sales1 = df["売上"].copy()
sales2 = df["売上"].copy()
sales3 = pd.Series([850, 920, np.nan, 780, 1200, 650, 920, np.nan])

# 2つのSeriesが同じか確認
print(sales1.equals(sales2))
print(sales1.equals(sales3))


# sales2の0番目の値を変更
sales2[0] = 1000

# 値を変更した後、再度同じか確認
print(sales1.equals(sales2))

True
False
False