## 1. DataFrameのインデックス（Indexing）

<img src="../images/image-27_1.png" width="800">

<br>

## 2. インデックス関連メソッド

<table align="left">
  <thead>
    <tr>
      <th>目的</th>
      <th>方法</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>インデックスを確認</td>
      <td><code>df.index</code></td>
    </tr>
    <tr>
      <td>インデックスをリストに変換</td>
      <td><code>df.index.tolist()</code></td>
    </tr>
    <tr>
      <td>インデックス名を確認</td>
      <td><code>df.index.name</code></td>
    </tr>
    <tr>
      <td>インデックス名を指定</td>
      <td><code>df.index.name = "名前"</code></td>
    </tr>
    <tr>
      <td>インデックスを直接変更</td>
      <td><code>df.index = [...]</code></td>
    </tr>
    <tr>
      <td>列 → インデックス</td>
      <td><code>set_index()</code></td>
    </tr>
    <tr>
      <td>インデックス → 列</td>
      <td><code>reset_index()</code></td>
    </tr>
    <tr>
      <td>既存のインデックスを削除</td>
      <td><code>reset_index(drop=True)</code></td>
    </tr>
    <tr>
      <td>インデックスを並べ替え</td>
      <td><code>sort_index()</code></td>
    </tr>
    <tr>
      <td>インデックスの行を削除</td>
      <td><code>drop()</code></td>
    </tr>
    <tr>
      <td>インデックスの値を変更</td>
      <td><code>rename(index={})</code></td>
    </tr>
    <tr>
      <td>重複インデックスを確認</td>
      <td><code>index.duplicated()</code></td>
    </tr>
    <tr>
      <td>インデックスを条件で選択</td>
      <td><code>df[df.index &gt;= 値]</code></td>
    </tr>
  </tbody>
</table>

<br clear="left">

<br>

In [1]:
# インデックス操作（ラベルインデックスであり、位置番号ではない）

# 現在のインデックスを確認
import pandas as pd


df = pd.DataFrame({
    "名前": ["千尋", "キキ", "ハウル"],
    "点数": [85, 90, 75]
})


print(df)

print(df.index)

    名前  点数
0   千尋  85
1   キキ  90
2  ハウル  75
RangeIndex(start=0, stop=3, step=1)

<br>

In [2]:
# インデックスの値をリストとして返す
print(df.index.tolist())

# インデックス名を確認、設定されていない場合はNone
print(df.index.name)

[0, 1, 2]
None

<br>

In [ ]:
# インデックス名を設定

df.index.name = "学生区分"

df

       名前  点数
学生区分
0      千尋  85
1      キキ  90
2     ハウル  75

<br>

In [ ]:
# インデックスを変更

df.index = ["学生1", "学生2", "学生3"]

df

      名前  点数
学生1   千尋  85
学生2   キキ  90
学生3  ハウル  75

<br>

#### - `set_index`：列 → インデックス

In [25]:
# DataFrameを確認

df = pd.DataFrame({
    "学生ID": [101, 102, 103],
    "名前": ["千尋", "キキ", "ハウル"],
    "点数": [85, 90, 75]
})


df

   学生ID   名前  点数
0   101   千尋  85
1   102   キキ  90
2   103  ハウル  75

<br>

In [26]:
# 列をインデックスに変更

df2 = df.set_index("学生ID")

df2

       名前  点数
学生ID
101    千尋  85
102    キキ  90
103   ハウル  75

<br>

In [27]:
# inplace=True → 元のDataFrame自体を直接変更

df.set_index("学生ID", inplace=True)  # 「学生ID」がインデックス名になる

df

       名前  点数
学生ID
101    千尋  85
102    キキ  90
103   ハウル  75

<br>

#### - `reset_index`：インデックス → 列

In [ ]:
# DataFrameを確認

df = pd.DataFrame({
    "学生ID": [101, 102, 103],
    "名前": ["千尋", "キキ", "ハウル"],
    "点数": [85, 90, 75]
})

df

   学生ID   名前  点数
0   101   千尋  85
1   102   キキ  90
2   103  ハウル  75

<br>

In [ ]:
# インデックスを列に変更

# namesを指定しない場合、列名はデフォルトで「index」になる

df2 = df.reset_index(names="番号")

df2

   番号  学生ID   名前  点数
0   0   101   千尋  85
1   1   102   キキ  90
2   2   103  ハウル  75

<br>

In [32]:
# 既存のインデックスを削除

df = pd.DataFrame({
    "名前": ["千尋", "キキ", "ハウル"]
}, index=[10, 20, 30])

df

     名前
10   千尋
20   キキ
30  ハウル

<br>

In [34]:
# reset_index()のデフォルトでは既存のインデックスを列に移動するが、
# drop=Trueを指定すると既存のインデックスを削除する

df2 = df.reset_index(drop=True)

df2

    名前
0   千尋
1   キキ
2  ハウル

<br>

In [35]:
# インデックスを並べ替え

df = pd.DataFrame({
    "名前": ["千尋", "キキ", "ハウル"]
}, index=[30, 10, 20])

df

     名前
30   千尋
10   キキ
20  ハウル

<br>

In [ ]:
# インデックスを昇順に並べ替え

df2 = df.sort_index()

df2

     名前
10   キキ
20  ハウル
30   千尋