## 1. `concat()` 関数

 : 同じ構造のデータを結合する

 - SQLのJOINとは異なる。
 - `concat`は単純に`軸を基準につなげるもの`であり、<br>
 共通キーを基準に（SQLのJOINに類似）データを結合する場合は、merge()またはjoin()を使用する。

https://pandas.pydata.org/docs/reference/api/pandas.concat.html

<div style="background-color:#f4f5f5; padding:0; color:#111111; font-family:monospace;">

<div style="background-color:#eaecee; padding:7px 16px;">
pd.<span style="color:#ff5c7a;">concat</span>(
</div>

<div style="background-color:#f4f5f5; padding:7px 48px;">
objs,
</div>

<div style="background-color:#eaecee; padding:7px 48px;">
axis=<span style="color:#ff7a00;">0</span>,
</div>

<div style="background-color:#f4f5f5; padding:7px 48px;">
join=<span style="color:#2e8b57;">"outer"</span>,
</div>

<div style="background-color:#eaecee; padding:7px 48px;">
ignore_index=False,
</div>

<div style="background-color:#f4f5f5; padding:7px 48px;">
keys=None
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
)
</div>

</div>

- axis=0 → 行を下方向に結合する

- axis=1 → 列を横方向に結合する

<br>

#### ※ 主なパラメータ

<table align="left">
  <thead>
    <tr>
      <th>パラメータ</th>
      <th>意味</th>
      <th>主な値</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>objs</code></td>
      <td>結合するオブジェクト</td>
      <td><code>[df1, df2]</code></td>
    </tr>
    <tr>
      <td><code>axis</code></td>
      <td>結合方向</td>
      <td><code>0, 1</code></td>
    </tr>
    <tr>
      <td><code>join</code></td>
      <td>もう一方の軸の処理方法</td>
      <td><code>"outer"</code>, <code>"inner"</code></td>
    </tr>
    <tr>
      <td><code>ignore_index</code></td>
      <td>既存のインデックスを無視</td>
      <td><code>True</code>, <code>False</code></td>
    </tr>
    <tr>
      <td><code>keys</code></td>
      <td>結合したデータに階層的インデックスを付与</td>
      <td><code>["A", "B"]</code></td>
    </tr>
  </tbody>
</table>

<br clear="left">

- `join="outer"` → すべての列（またはインデックス）を維持する  
- `join="inner"` → 共通する列（またはインデックス）のみ維持する  
- SQLの`JOIN`のように共通キーを基準に結合する機能ではない。

<br>

In [2]:
import pandas as pd


df1 = pd.DataFrame({
    "名前": ["千尋", "キキ"],
    "点数": [80, 90]
})


df2 = pd.DataFrame({
    "名前": ["ハウル", "ソフィー"],
    "点数": [85, 95]
})


display(df1)
display(df2)

   名前  点数
0  千尋  80
1  キキ  90

     名前  点数
0   ハウル  85
1  ソフィー  95

<br>

#### - `ignore_index=False`：デフォルト値 <br> → インデックスを`維持`

In [2]:
# axis=0 → 上下方向に結合（基本）→ 行を追加

df = pd.concat(
    [df1, df2],
    ignore_index=False,
    axis=0
) 

display(df)

     名前  点数
0    千尋  80
1    キキ  90
0   ハウル  85
1  ソフィー  95

<br>

#### - `ignore_index=True` <br> → インデックスを`リセット`

In [3]:
df = pd.concat(
    [df1, df2],
    ignore_index=True,
    axis=0
)

display(df)

     名前  点数
0    千尋  80
1    キキ  90
2   ハウル  85
3  ソフィー  95

<br>

#### - `axis=1` <br> → 省略した場合の`デフォルト値`は `0`

In [3]:
# axis=1 → 左右に結合 → 列を追加

df = pd.concat([df1, df2], axis=1)

display(df)

   名前  点数    名前  点数
0  千尋  80   ハウル  85
1  キキ  90  ソフィー  95

<br>

#### `join="outer"` vs `join="inner"`

`join`は、**全体を維持するか、共通部分だけを維持するか**を決定する。

In [4]:
df1 = pd.DataFrame({
    "名前": ["千尋", "キキ"],
    "点数": [80, 90]
})


df2 = pd.DataFrame({
    "名前": ["ハウル", "ソフィー"],
    "等級": ["A", "B"]
})


display(df1)
display(df2)

   名前  点数
0  千尋  80
1  キキ  90

     名前 等級
0   ハウル  A
1  ソフィー  B

#### → 2つのDataFrameで共通する列は、`「名前」`列のみである。

##### -  join="outer"の例 <br> (両方のDataFrameに存在するすべての列を維持する)

In [5]:
# joinを省略した場合、デフォルト値は"outer"

df = pd.concat(
    [df1, df2],
    join="outer",
    ignore_index=True
)

display(df)

     名前    点数   等級
0    千尋  80.0  NaN
1    キキ  90.0  NaN
2   ハウル   NaN    A
3  ソフィー   NaN    B

<br>

##### -  join="inner"の例 <br> (両方のDataFrameに共通して存在する列のみ維持する)

In [6]:
df = pd.concat(
    [df1, df2],
    join="inner",
    ignore_index=True
)

display(df)

     名前
0    千尋
1    キキ
2   ハウル
3  ソフィー

##### - `axis=1`：列方向に結合

In [7]:
import pandas as pd


df = pd.DataFrame({
    "名前": ["千尋", "キキ", "ハウル", "ソフィー"],
    "点数": [90, 80, 95, 70]
})


grade = pd.DataFrame({
    "等級": ["A", "B", "A", "C"]
})


# axis=1 → インデックスを基準に左右へ結合
result = pd.concat([df, grade], axis=1)

display(result)

     名前  点数 等級
0    千尋  90  A
1    キキ  80  B
2   ハウル  95  A
3  ソフィー  70  C

<br>

##### 行数（インデックス）が一致しない場合 <br> → 存在しない値がNaNで補われる

In [ ]:
df = pd.DataFrame({
    "名前": ["千尋", "キキ", "ハウル", "ソフィー"],
    "点数": [90, 80, 95, 70]
})


grade2 = pd.DataFrame({
    "等級": ["A", "B", "A"]
})


result = pd.concat([df, grade2], axis=1)

display(result)

     名前  点数   等級
0    千尋  90    A
1    キキ  80    B
2   ハウル  95    A
3  ソフィー  70  NaN