## 1. `concat()` 関数

 : 同じ構造のデータを結合する

 - SQLのJOINとは異なる。
 - `concat`は単純に`軸を基準につなげるもの`であり、<br>
 共通キーを基準に（SQLのJOINに類似）データを結合する場合は、merge()またはjoin()を使用する。

https://pandas.pydata.org/docs/reference/api/pandas.concat.html

<div style="background-color:#f4f5f5; padding:0; color:#111111; font-family:monospace;">

<div style="background-color:#eaecee; padding:7px 16px;">
pd.<span style="color:#ff5c7a;">concat</span>(
</div>

<div style="background-color:#f4f5f5; padding:7px 48px;">
objs,
</div>

<div style="background-color:#eaecee; padding:7px 48px;">
axis=<span style="color:#ff7a00;">0</span>,
</div>

<div style="background-color:#f4f5f5; padding:7px 48px;">
join=<span style="color:#2e8b57;">"outer"</span>,
</div>

<div style="background-color:#eaecee; padding:7px 48px;">
ignore_index=False,
</div>

<div style="background-color:#f4f5f5; padding:7px 48px;">
keys=None
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
)
</div>

</div>

- axis=0 → 行を下方向に結合する

- axis=1 → 列を横方向に結合する

<br>

#### ※ 主なパラメータ

<table align="left">
  <thead>
    <tr>
      <th>パラメータ</th>
      <th>意味</th>
      <th>主な値</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>objs</code></td>
      <td>結合するオブジェクト</td>
      <td><code>[df1, df2]</code></td>
    </tr>
    <tr>
      <td><code>axis</code></td>
      <td>結合方向</td>
      <td><code>0, 1</code></td>
    </tr>
    <tr>
      <td><code>join</code></td>
      <td>もう一方の軸の処理方法</td>
      <td><code>"outer"</code>, <code>"inner"</code></td>
    </tr>
    <tr>
      <td><code>ignore_index</code></td>
      <td>既存のインデックスを無視</td>
      <td><code>True</code>, <code>False</code></td>
    </tr>
    <tr>
      <td><code>keys</code></td>
      <td>結合したデータに階層的インデックスを付与</td>
      <td><code>["A", "B"]</code></td>
    </tr>
  </tbody>
</table>

<br clear="left">

- `join="outer"` → すべての列（またはインデックス）を維持する  
- `join="inner"` → 共通する列（またはインデックス）のみ維持する  
- SQLの`JOIN`のように共通キーを基準に結合する機能ではない。

<br>

In [2]:
import pandas as pd


df1 = pd.DataFrame({
    "名前": ["千尋", "キキ"],
    "点数": [80, 90]
})


df2 = pd.DataFrame({
    "名前": ["ハウル", "ソフィー"],
    "点数": [85, 95]
})


display(df1)
display(df2)

   名前  点数
0  千尋  80
1  キキ  90

     名前  点数
0   ハウル  85
1  ソフィー  95

<br>

#### - `ignore_index=False`：デフォルト値 <br> → インデックスを`維持`

In [3]:
# axis=0 → 上下方向に結合（基本）→ 行を追加

df = pd.concat(
    [df1, df2],
    ignore_index=False,
    axis=0
) 

display(df)

     名前  点数
0    千尋  80
1    キキ  90
0   ハウル  85
1  ソフィー  95

<br>

#### - `ignore_index=True` <br> → インデックスを`リセット`

In [4]:
df = pd.concat(
    [df1, df2],
    ignore_index=True,
    axis=0
)

display(df)

     名前  点数
0    千尋  80
1    キキ  90
2   ハウル  85
3  ソフィー  95

<br>

#### - `axis=1` <br> → 省略した場合の`デフォルト値`は `0`

In [5]:
# axis=1 → 左右に結合 → 列を追加

df = pd.concat([df1, df2], axis=1)

display(df)

   名前  点数    名前  点数
0  千尋  80   ハウル  85
1  キキ  90  ソフィー  95

<br>

#### ※ `join="outer"` vs `join="inner"`

`join`は、**全体を維持するか、共通部分だけを維持するか**を決定する。

In [6]:
df1 = pd.DataFrame({
    "名前": ["千尋", "キキ"],
    "点数": [80, 90]
})


df2 = pd.DataFrame({
    "名前": ["ハウル", "ソフィー"],
    "等級": ["A", "B"]
})


display(df1)
display(df2)

   名前  点数
0  千尋  80
1  キキ  90

     名前 等級
0   ハウル  A
1  ソフィー  B

#### → 2つのDataFrameで共通する列は、`「名前」`列のみである。

<br>

#### - join="outer"の例 <br> (両方のDataFrameに存在するすべての列を維持する)

In [7]:
# joinを省略した場合、デフォルト値は"outer"

df = pd.concat(
    [df1, df2],
    join="outer",
    ignore_index=True
)

display(df)

     名前    点数   等級
0    千尋  80.0  NaN
1    キキ  90.0  NaN
2   ハウル   NaN    A
3  ソフィー   NaN    B

<br>

#### - join="inner"の例 <br> (両方のDataFrameに共通して存在する列のみ維持する)

In [8]:
df = pd.concat(
    [df1, df2],
    join="inner",
    ignore_index=True
)

display(df)

     名前
0    千尋
1    キキ
2   ハウル
3  ソフィー

<br>

#### - `axis=1`：列方向に結合

In [9]:
import pandas as pd


df = pd.DataFrame({
    "名前": ["千尋", "キキ", "ハウル", "ソフィー"],
    "点数": [90, 80, 95, 70]
})


grade = pd.DataFrame({
    "等級": ["A", "B", "A", "C"]
})


# axis=1 → インデックスを基準に左右へ結合
result = pd.concat([df, grade], axis=1)

display(result)

     名前  点数 等級
0    千尋  90  A
1    キキ  80  B
2   ハウル  95  A
3  ソフィー  70  C

<br>

#### - 行数（インデックス）が一致しない場合 <br> → 存在しない値がNaNで補われる

In [10]:
df = pd.DataFrame({
    "名前": ["千尋", "キキ", "ハウル", "ソフィー"],
    "点数": [90, 80, 95, 70]
})


grade2 = pd.DataFrame({
    "等級": ["A", "B", "A"]
})


result = pd.concat([df, grade2], axis=1)

display(result)

     名前  点数   等級
0    千尋  90    A
1    キキ  80    B
2   ハウル  95    A
3  ソフィー  70  NaN

<br>

In [ ]:
# `join="inner"`：両方に共通するインデックスだけを残して結合する。

pd.concat([df, grade2], axis=1, join="inner")

    名前  点数 等級
0   千尋  90  A
1   キキ  80  B
2  ハウル  95  A

<br>

## 2. merge()関数

- `merge()`は、2つのDataFrameに共通する列（キー）を基準にデータを結合するときに使用する関数である。

- SQLの`JOIN`を使用した経験があれば、`merge()`は理解しやすい (基本的な考え方はSQLの`JOIN`と同じである)

https://pandas.pydata.org/docs/reference/api/pandas.merge.html

<br>

<div style="font-family: Consolas, monospace; color: black; width: 100%;">

<div style="background-color:#f4f5f5; padding:6px 12px;">
pd.<span style="color:#d63384;">merge</span>(
</div>

<div style="background-color:#eaecee; padding:6px 36px;">
left,
</div>

<div style="background-color:#f4f5f5; padding:6px 36px;">
right,
</div>

<div style="background-color:#eaecee; padding:6px 36px;">
how=<span style="color:#008000;">"inner"</span>,
</div>

<div style="background-color:#f4f5f5; padding:6px 36px;">
on=None,
</div>

<div style="background-color:#eaecee; padding:6px 36px;">
left_on=None,
</div>

<div style="background-color:#f4f5f5; padding:6px 36px;">
right_on=None,
</div>

<div style="background-color:#eaecee; padding:6px 36px;">
suffixes=(<span style="color:#008000;">"_x"</span>, <span style="color:#008000;">"_y"</span>)
</div>

<div style="background-color:#f4f5f5; padding:6px 12px;">
)
</div>

</div>

<br>

#### ※ 主な引数

<table align="left">
    <tr>
        <th>引数</th>
        <th>意味</th>
        <th>主な値</th>
    </tr>
    <tr>
        <td><code>left</code></td>
        <td>左側のDataFrame</td>
        <td><code>df1</code></td>
    </tr>
    <tr>
        <td><code>right</code></td>
        <td>右側のDataFrame</td>
        <td><code>df2</code></td>
    </tr>
    <tr>
        <td><code>how</code></td>
        <td>結合方法</td>
        <td><code>"inner"</code>、<code>"left"</code>、<code>"right"</code>、<code>"outer"</code></td>
    </tr>
    <tr>
        <td><code>on</code></td>
        <td>両方に共通して存在する結合キーとなる列</td>
        <td><code>"顧客ID"</code></td>
    </tr>
    <tr>
        <td><code>left_on</code></td>
        <td>左側のDataFrameで基準となる列</td>
        <td><code>"顧客番号"</code></td>
    </tr>
    <tr>
        <td><code>right_on</code></td>
        <td>右側のDataFrameで基準となる列</td>
        <td><code>"会員番号"</code></td>
    </tr>
    <tr>
        <td><code>suffixes</code></td>
        <td>同じ名前の列に付ける接尾辞</td>
        <td><code>("_x", "_y")</code></td>
    </tr>
</table>

<br clear="left">

<br>

#### # merge()によるDataFrameの結合

2つのDataFrameを`顧客ID`をキーとして結合する。

結合方法は`how`引数で指定し、`inner`・`left`・`right`・`outer`の4種類を比較する。

In [12]:
import pandas as pd


df_customer = pd.DataFrame({
    "顧客ID": [101, 102, 103, 104],
    "名前": ["千尋", "ハウル", "ソフィー", "アシタカ"]
})

df_score = pd.DataFrame({
    "顧客ID": [101, 102, 103, 105],
    "点数": [90, 80, 95, 70]
})


display(df_customer)
display(df_score)

   顧客ID    名前
0   101    千尋
1   102   ハウル
2   103  ソフィー
3   104  アシタカ

   顧客ID  点数
0   101  90
1   102  80
2   103  95
3   105  70

<br>

#### 1. inner結合

`inner`は、両方のDataFrameに共通して存在するキーのデータだけを結合する。

この例では、両方に存在する`顧客ID`の`101・102・103`だけが結果に残る。

In [13]:
result = pd.merge(
    df_customer,
    df_score,
    on="顧客ID",
    how="inner"  # inner（デフォルト）、left、right、outer
)

display(result)

   顧客ID    名前  点数
0   101    千尋  90
1   102   ハウル  80
2   103  ソフィー  95

<br>

#### 2. left結合

`left`は、左側のDataFrameを基準にすべてのデータを残す。

右側に一致するデータがない場合は、該当する値が`NaN`になる。

In [14]:
result = pd.merge(
    df_customer,
    df_score,
    on="顧客ID",
    how="left"
)

display(result)

   顧客ID    名前    点数
0   101    千尋  90.0
1   102   ハウル  80.0
2   103  ソフィー  95.0
3   104  アシタカ   NaN

<br>

#### 3. right結合

`right`は、右側のDataFrameを基準にすべてのデータを残す。

左側に一致するデータがない場合は、該当する値が`NaN`になる。

In [15]:
result = pd.merge(
    df_customer,
    df_score,
    on="顧客ID",
    how="right"
)

display(result)

   顧客ID    名前  点数
0   101    千尋  90
1   102   ハウル  80
2   103  ソフィー  95
3   105   NaN  70

<br>

#### 4. outer結合

`outer`は、左右両方のDataFrameに存在するすべてのキーを残す。

どちらか一方にしか存在しないデータは、対応する値が`NaN`になる。

In [16]:
result = pd.merge(
    df_customer,
    df_score,
    on="顧客ID",
    how="outer"
)

display(result)

   顧客ID    名前    点数
0   101    千尋  90.0
1   102   ハウル  80.0
2   103  ソフィー  95.0
3   104  アシタカ   NaN
4   105   NaN  70.0

<br>

#### ※ 結合方法の違い

- `inner`：両方に存在するデータのみ
- `left`：左側のデータをすべて残す
- `right`：右側のデータをすべて残す
- `outer`：左右両方のデータをすべて残す

<br>

※ pandasライブラリには、`merge()`関数と似た機能を持つ`DataFrame.merge()`、`DataFrame.join()`などのメソッドもある。

似た機能を持つ`merge()`メソッドや`join()`メソッドが存在するのは、使用する場面やコードの書き方が少し異なるためである。

基本的には、まず`merge()`関数を使えるようになれば十分である。