## 1. `concat()` 関数

 : 同じ構造のデータを結合する

 - SQLのJOINとは異なる。
 - `concat`は単純に`軸を基準につなげるもの`であり、<br>
 共通キーを基準に（SQLのJOINに類似）データを結合する場合は、merge()またはjoin()を使用する。

https://pandas.pydata.org/docs/reference/api/pandas.concat.html

<div style="background-color:#f4f5f5; padding:0; color:#111111; font-family:monospace;">

<div style="background-color:#eaecee; padding:7px 16px;">
pd.<span style="color:#ff5c7a;">concat</span>(
</div>

<div style="background-color:#f4f5f5; padding:7px 48px;">
objs,
</div>

<div style="background-color:#eaecee; padding:7px 48px;">
axis=<span style="color:#ff7a00;">0</span>,
</div>

<div style="background-color:#f4f5f5; padding:7px 48px;">
join=<span style="color:#2e8b57;">"outer"</span>,
</div>

<div style="background-color:#eaecee; padding:7px 48px;">
ignore_index=False,
</div>

<div style="background-color:#f4f5f5; padding:7px 48px;">
keys=None
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
)
</div>

</div>

- axis=0 → 行を下方向に結合する

- axis=1 → 列を横方向に結合する

<br>

#### ※ 主なパラメータ

<table align="left">
  <thead>
    <tr>
      <th>パラメータ</th>
      <th>意味</th>
      <th>主な値</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>objs</code></td>
      <td>結合するオブジェクト</td>
      <td><code>[df1, df2]</code></td>
    </tr>
    <tr>
      <td><code>axis</code></td>
      <td>結合方向</td>
      <td><code>0, 1</code></td>
    </tr>
    <tr>
      <td><code>join</code></td>
      <td>もう一方の軸の処理方法</td>
      <td><code>"outer"</code>, <code>"inner"</code></td>
    </tr>
    <tr>
      <td><code>ignore_index</code></td>
      <td>既存のインデックスを無視</td>
      <td><code>True</code>, <code>False</code></td>
    </tr>
    <tr>
      <td><code>keys</code></td>
      <td>結合したデータに階層的インデックスを付与</td>
      <td><code>["A", "B"]</code></td>
    </tr>
  </tbody>
</table>

<br clear="left">

- `join="outer"` → すべての列（またはインデックス）を維持する  
- `join="inner"` → 共通する列（またはインデックス）のみ維持する  
- SQLの`JOIN`のように共通キーを基準に結合する機能ではない。

<br>

In [1]:
import pandas as pd


df1 = pd.DataFrame({
    "名前": ["千尋", "キキ"],
    "点数": [80, 90]
})


df2 = pd.DataFrame({
    "名前": ["ハウル", "ソフィー"],
    "点数": [85, 95]
})


display(df1)
display(df2)

   名前  点数
0  千尋  80
1  キキ  90

     名前  点数
0   ハウル  85
1  ソフィー  95

<br>

#### - `ignore_index=False`：デフォルト値 <br> → インデックスを`維持`

In [2]:
# axis=0 → 上下方向に結合（基本）→ 行を追加

df = pd.concat(
    [df1, df2],
    ignore_index=False,
    axis=0
) 

display(df)

     名前  点数
0    千尋  80
1    キキ  90
0   ハウル  85
1  ソフィー  95

<br>

#### - `ignore_index=True` <br> → インデックスを`リセット`

In [3]:
df = pd.concat(
    [df1, df2],
    ignore_index=True,
    axis=0
)

display(df)

     名前  点数
0    千尋  80
1    キキ  90
2   ハウル  85
3  ソフィー  95