<img src="../images/image-11.png" width="800">

#### # `iloc[]`インデックス vs `loc[]`インデックス vs `[]`インデックス演算子

| 方法 | 行の選択 | 列の選択 |
|---|---|---|
| `loc[]` | ラベル | ラベル |
| `iloc[]` | 数値位置 | 数値位置 |
| `df[]` | 条件・スライスなど | 列名 |

#### 1) 行と列を同時に選択

- `loc[]` インデックス → `ラベル`を基準に行・列を選択
- `iloc[]` インデックス → `数値位置`を基準に行・列を選択

#### 2) 行・列のどちらか一方を選択

- `df[]` 演算子
  - `列名` → 列を選択：列を選択すると → 行はすべて → 特定の列のすべての行
  - `条件式` → 行を選択：行を選択すると → 列はすべて → 特定の行のすべての列
  - `スライス` → 行を選択：行を選択すると → 列はすべて → 特定の行のすべての列

`df[]`は基本的に`一方の軸だけを選択`し、選択していない軸は`すべて`となる。

#### 実習用DataFrame

In [1]:
import pandas as pd

df = pd.DataFrame({
    "名前": ["千尋", "キキ", "ハウル", "ソフィー", "アシタカ"],
    "学年": [1, 2, 1, 3, 2],
    "点数": [85, 92, 78, 95, 88]
}, index=["A", "B", "C", "D", "E"])

print(df)

     名前  学年  点数
A    千尋   1  85
B    キキ   2  92
C   ハウル   1  78
D  ソフィー   3  95
E  アシタカ   2  88

`行ラベルインデックス` → A, B, C, D, E <br>
`行位置` → 0, 1, 2, 3, 4

`列名` → 名前, 学年, 点数 <br>
`列位置` → 0, 1, 2

## 1. 行・列の選択

#### 1) `loc`インデックス：行インデックス、列名を使用

In [ ]:
# loc[行インデックス, 列名]

print(df.loc["B", "点数"])

92

In [4]:
# 複数行、複数列を選択する場合は[]内にリストを使用

print(df.loc[["B", "D"], ["名前", "点数"]])

     名前  点数
B    キキ  92
D  ソフィー  95

In [5]:
# loc[行インデックスのスライス, 列名のスライス]

df.loc["B":"D", "名前":"点数"]

     名前  学年  点数
B    キキ   2  92
C   ハウル   1  78
D  ソフィー   3  95

#### 2) `iloc`インデックス：行位置、列位置を使用

In [6]:
# iloc[行位置, 列位置]

print(df.iloc[1, 2])

92

In [7]:
# 複数行、複数列を選択

print(df.iloc[[1, 3], [0, 2]])

     名前  点数
B    キキ  92
D  ソフィー  95

In [10]:
# iloc[行位置のスライス, 列位置のスライス]

df.iloc[1:4, 0:2]

     名前  学年
B    キキ   2
C   ハウル   1
D  ソフィー   3

## 2. `[]` インデックス演算子

`[値]` → `列を選択`  
`[式]` → `行を選択`

#### 1) 列の選択

- `df[数値]`  
  「列名が`0`である列」

```python
# 0番目の列ではない。0番目の列はiloc[]インデックスを使用する必要がある
df[0]  # error
```

- `df["名前"]`  
  `列名`で指定

```python
df["名前"]

# 2つ以上の列は[]の中にリストを使用し、[]の中に1つの値として入力
df[["名前", "点数"]]

# error! []演算子の中には1つの式のみ指定できる
# df["名前", "点数"]
```

`[]`演算子の引数に`リスト型`を指定した場合、1つ以上の列を返すため、戻り値は`DataFrame型`となる。  
`[]`演算子に`スカラーの列名`を指定した場合、戻り値は`Series型`となる。

```python
df["点数"]             # Series
df[["名前", "点数"]]    # DataFrame

# 1つの列でもリスト形式で指定すると、1列のDataFrame型が返される
df[["点数"]]            # DataFrame
```

#### 2) 行の選択

##### 1) `df[スライス]`：`[]`演算子内にスライス式

In [17]:
df[1:4]  # 行を位置基準で1番目から3番目まで選択

     名前  学年  点数
B    キキ   2  92
C   ハウル   1  78
D  ソフィー   3  95

##### 2) `df[列条件]`：`[]`演算子内に列条件式

In [18]:
df[df["点数"] >= 90]  # 条件に一致する行を選択

     名前  学年  点数
B    キキ   2  92
D  ソフィー   3  95

In [19]:
# `df[df["点数"] >= 90]`を分解して表現すると、

temp = df["点数"]
df[temp >= 90]

     名前  学年  点数
B    キキ   2  92
D  ソフィー   3  95

次のコードは`エラー`

```python
df["点数" > 90]
```

`"点数" > 90`は、`文字列 > 数値`という式であるため、`エラー`が発生する。

上記の`df["点数"]`の戻り値は`pandas.Series型`である。

Pythonでは、`リスト > 数値`のような比較では`エラー`が発生するが、Pandasの`pandas.Series > 数値`は`エラー`にならない。

```python
# error
[5, 10, 15, 20] > 10
```

```python
# エラーが発生しないように実行する場合は内包表記を使用
[x > 10 for x in [5, 10, 15, 20]]
```

```python
# エラーではなく、各値を比較した結果を返す
# Series内部で比較演算を実行
pd.Series([5, 10, 15, 20]) > 10
```

0    False <br>
1    False <br>
2     True <br>
3     True <br>
dtype: bool <br>

Pythonの`list > 演算子`をリスト全体に適用しても、要素ごとの比較は行われない。  
そのため、`リスト内包表記`または`for文`を使用する必要がある。

Pandasの`Series`は、内部的にNumPyの`配列演算`を活用するため、同じ演算子を各要素に適用できる。

| 方法 | 例 | 基準 | 主な選択対象 |
|---|---|---|---|
| `loc[]` | `df.loc["B", "点数"]` | ラベル | 行 + 列 |
| `iloc[]` | `df.iloc[1, 2]` | 数値位置 | 行 + 列 |
| `[]` | `df["点数"]` | 列名 | 列 |
| `[]` スライス | `df[1:4]` | 数値位置の範囲 | 行 |
| `[]` 条件 | `df[df["点数"] >= 90]` | 条件 | 行 |