ターミナルで`seaborn`ライブラリをインストールする。

- `seaborn`はPandasのDataFrameを利用して`統計グラフ`を簡単に描画できるPythonの`可視化ライブラ`リである。  
- 可視化に使用できる`実習用のサンプルデータセット`も提供している。

```bash
pip install seaborn
```

```python
import seaborn as sns

mpg = sns.load_dataset("mpg")
mpg.info()
```

In [ ]:
import seaborn as sns
mpg = sns.load_dataset('mpg')
mpg.info()

```py
<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    str
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB
```

In [5]:
mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

#### 各列の意味

| 列名 | 意味 |
|---|---|
| `mpg` | 燃費 |
| `cylinders` | シリンダー数 |
| `displacement` | 排気量 |
| `horsepower` | 馬力 |
| `weight` | 車両重量 |
| `acceleration` | 加速度 |
| `model_year` | 発売年度 |
| `origin` | 生産地域 |
| `name` | 自動車名 |

#### 問題 1. `[]`で列を選択

`mpg` DataFrameから`mpg`列のみを選択して出力しなさい。

In [6]:
mpg["mpg"]

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

#### 問題 2. `[]`で複数の列を選択

`mpg` DataFrameから`mpg`、`weight`、`origin`の3つの列を選択して出力しなさい。

In [10]:
mpg[["mpg", "weight", "origin"]]

      mpg  weight  origin
0    18.0    3504     usa
1    15.0    3693     usa
2    18.0    3436     usa
3    16.0    3433     usa
4    17.0    3449     usa
..    ...     ...     ...
393  27.0    2790     usa
394  44.0    2130  europe
395  32.0    2295     usa
396  28.0    2625     usa
397  31.0    2720     usa

[398 rows x 3 columns]

#### 問題 3. `iloc`で特定の行を選択

`mpg`から`10番目の行`のデータを出力しなさい。  
ただし、数値位置を使用する`iloc`を使いなさい。

In [17]:
mpg.iloc[9]

mpg                           15.0
cylinders                        8
displacement                 390.0
horsepower                   190.0
weight                        3850
acceleration                   8.5
model_year                      70
origin                         usa
name            amc ambassador dpl
Name: 9, dtype: object

#### 問題 4. `iloc`で行 + 列を選択

`mpg`から`3番目の行`の`1番目の列`の値を出力しなさい。

In [16]:
mpg.iloc[2,0]

np.float64(18.0)

#### 問題 5. `iloc`で行 + 列をスライス

`mpg`から`1～5番目の行`と`1～3番目の列`を選択して出力しなさい。

In [20]:
mpg.iloc[[0,5], [0,3]]

    mpg  horsepower
0  18.0       130.0
5  15.0       198.0

#### 問題 6. `loc`で特定の行 + 列を選択

`mpg`から`インデックスが10の行`の`mpg`の値を出力しなさい。

In [22]:
mpg.loc[10, "mpg"]

np.float64(15.0)

#### 問題 7. `loc`で複数の行 ＋ 列を選択


`インデックスが10〜15の行`で

- `mpg`

- `weight`

- `origin`

`列だけ`を選択して出力しなさい。

In [26]:
mpg.loc[10:15, ["mpg", "weight", "origin"]]

     mpg  weight origin
10  15.0    3563    usa
11  14.0    3609    usa
12  15.0    3761    usa
13  14.0    3086    usa
14  24.0    2372  japan
15  22.0    2833    usa

#### 問題 8. `loc` スライシング

`mpg` において、`インデックス 10 から 15 まで`のデータを選択しなさい。

In [29]:
mpg.loc[10:15]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
10,15.0,8,383.0,170.0,3563,10.0,70,usa,dodge challenger se
11,14.0,8,340.0,160.0,3609,8.0,70,usa,plymouth 'cuda 340
12,15.0,8,400.0,150.0,3761,9.5,70,usa,chevrolet monte carlo
13,14.0,8,455.0,225.0,3086,10.0,70,usa,buick estate wagon (sw)
14,24.0,4,113.0,95.0,2372,15.0,70,japan,toyota corona mark ii
15,22.0,6,198.0,95.0,2833,15.5,70,usa,plymouth duster

#### 問題9. `条件`で`行を選択`

`mpg`で、`mpg`が`30以上`の自動車のみを選択しなさい。

In [35]:
mpg.loc[mpg["mpg"] >= 30]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
51,30.0,4,79.0,70.0,2074,19.5,71,europe,peugeot 304
52,30.0,4,88.0,76.0,2065,14.5,71,europe,fiat 124b
53,31.0,4,71.0,65.0,1773,19.0,71,japan,toyota corolla 1200
54,35.0,4,72.0,69.0,1613,18.0,71,japan,datsun 1200
129,31.0,4,79.0,67.0,1950,19.0,74,japan,datsun b210
...,...,...,...,...,...,...,...,...,...
390,32.0,4,144.0,96.0,2665,13.9,82,japan,toyota celica gt
391,36.0,4,135.0,84.0,2370,13.0,82,usa,dodge charger 2.2
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

#### 問題 10. `条件` + `列の選択`

`mpg`が`30以上`の自動車の`name`と`mpg`のみを出力しなさい。

In [36]:
mpg.loc[mpg["mpg"] >= 30, ["name", "mpg"]]

                    name   mpg
51           peugeot 304  30.0
52             fiat 124b  30.0
53   toyota corolla 1200  31.0
54           datsun 1200  35.0
129          datsun b210  31.0
..                   ...   ...
390     toyota celica gt  32.0
391    dodge charger 2.2  36.0
394            vw pickup  44.0
395        dodge rampage  32.0
397           chevy s-10  31.0

[92 rows x 2 columns]

#### 問題 11. `2つの条件`で`行を選択`する

`mpg`が`30以上`で、`weight`が`2000以下`の自動車のみを出力しなさい。

In [38]:
mpg.loc[(mpg["mpg"] >= 30) & (mpg["weight"] <= 2000)]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
53,31.0,4,71.0,65.0,1773,19.0,71,japan,toyota corolla 1200
54,35.0,4,72.0,69.0,1613,18.0,71,japan,datsun 1200
129,31.0,4,79.0,67.0,1950,19.0,74,japan,datsun b210
131,32.0,4,71.0,65.0,1836,21.0,74,japan,toyota corolla 1200
144,31.0,4,76.0,52.0,1649,16.5,74,japan,toyota corona
151,31.0,4,79.0,67.0,2000,16.0,74,europe,fiat x1.9
181,33.0,4,91.0,53.0,1795,17.5,75,japan,honda civic cvcc
198,33.0,4,91.0,53.0,1795,17.4,76,japan,honda civic
204,32.0,4,85.0,70.0,1990,17.0,76,japan,datsun b-210
218,36.0,4,79.0,58.0,1825,18.6,77,europe,renault 5 gtl
220,33.5,4,85.0,70.0,1945,16.8,77,japan,datsun f-10 hatchback
239,30.0,4,97.0,67.0,1985,16.4,77,japan,subaru dl
244,43.1,4,90.0,48.0,1985,21.5,78,europe,volkswagen rabbit custom diesel
245,36.1,4,98.0,66.0,1800,14.4,78,usa,ford fiesta
246,32.8,4,78.0,52.0,1985,19.4,78,japan,mazda glc deluxe
248,36.1,4,91.0,60.0,1800,16.4,78,japan,honda civic cvcc
278,31.5,4,89.0,71.0,1990,14.9,78,europe,volkswagen scirocco
293,31.9,4,89.0,71.0,1925,14.0,79,europe,vw rabbit custom
294,34.1,4,86.0,65.0,1975,15.2,79,japan,maxda glc deluxe
295,35.7,4,98.0,80.0,1915,14.4,79,usa,dodge colt hatchback custom
310,38.1,4,89.0,60.0,1968,18.8,80,japan,toyota corolla tercel
329,44.6,4,91.0,67.0,1850,13.8,80,japan,honda civic 1500 gl
330,40.9,4,85.0,NaN,1835,17.3,80,europe,renault lecar deluxe
343,39.1,4,79.0,58.0,1755,16.9,81,japan,toyota starlet
344,39.0,4,86.0,64.0,1875,16.4,81,usa,plymouth champ
345,35.1,4,81.0,60.0,1760,16.1,81,japan,honda civic 1300
347,37.0,4,85.0,65.0,1975,19.4,81,japan,datsun 210 mpg
349,34.1,4,91.0,68.0,1985,16.0,81,japan,mazda glc 4
375,36.0,4,105.0,74.0,1980,15.3,82,europe,volkswagen rabbit l
377,31.0,4,91.0,68.0,1970,17.6,82,japan,mazda glc custom
383,38.0,4,91.0,67.0,1965,15.0,82,japan,honda civic
384,32.0,4,91.0,67.0,1965,15.7,82,japan,honda civic (auto)
385,38.0,4,91.0,67.0,1995,16.2,82,japan,datsun 310 gx

#### 問題12. 次の`コードの意味`を`説明`しなさい。

```py
df.loc[10:15, ['mpg', 'weight']]

df.iloc[10:15, 0:2]

df['mpg']

df[10:15]

df[df['mpg'] >= 30]
```

模範解答

```py
# df.loc[10:15, ['mpg', 'weight']]
# インデックス名が 10 から 15 までの行における、mpg 列と weight 列のデータを取得する。（末尾 15 を含む）

# df.iloc[10:15, 0:2]
# 11〜15 番目の行（インデックス 10〜14）と、1〜2 番目の列（インデックス 0〜1）のデータを取得する。（末尾 15, 2 を含まない）

# df['mpg']
# mpg 列の全データを取得する。

# df[10:15]
# インデックス 10 から 14 までの行（11〜15 番目の行）を取得する。（末尾 15 を含まない）

# df[df['mpg'] >= 30]
# mpg 列の値が 30 以上である行のみを抽出して取得する。
```